// 
// Decompiled by Procyon v0.5.30
// 

package com.bdoemu.gameserver.model.team.guild.enums;

public enum EGuildContractNotifyType {
    PAYMENTS_BEGIN,
    MONEY_DEPOSIT,
    MONEY_COLLECTION,
    HIRE_RENEWAL,
    EXPIRATION,
    AGREEMENT_GUILD_OPEN,
    PAYMENTS_STATUS,
    MEMBER_LEFT,
    MEMBER_EXPELLED,
    UPGRADED,
    AUCTION_BET_MONEY_STATUS,
    AUCTION_BET_MONEY_STATUS2,
    AUCTION_BET_RESULT,
    MONEY_USED_IN_GUILD_STORE,
    INCENTIVE_PAID,
    HOUSE_FEE_PAID,
    CREATED,
    GUILDQUEST_ACCEPT,
    GUILDQUEST_COMPLETE,
    LORD_MOVETAX_TO_GUILDMONEY,
    DECLARE_WAR_CONSUME,
    DECLARE_WAR_CONSUME2,
    UNK1,
    UNK2,
    UNK3,
    UNK4,
    GUILDQUEST_REFRESH,
    MORALE_UP,
    MORALE_DOWN,
    CHEERING,
    GUILDQUEST_CONTRACT_EXPIRED,
    AUTODESTROYBUILD1,
    AUTODESTROYBUILD2;
}
