// 
// Decompiled by Procyon v0.5.30
// 

package com.bdoemu.core.network.sendable.utils;

import com.bdoemu.commons.network.SendByteBuffer;
import com.bdoemu.gameserver.model.creature.player.Player;
import com.bdoemu.gameserver.model.creature.player.appearance.holders.AppearanceBodyHolder;
import com.bdoemu.gameserver.model.creature.player.appearance.holders.AppearanceFaceHolder;
import com.bdoemu.gameserver.model.creature.player.appearance.holders.AppearanceHairHolder;
import com.bdoemu.gameserver.model.creature.player.appearance.holders.AppearanceTattooHolder;
import com.bdoemu.gameserver.model.creature.player.enums.EClassType;
import com.bdoemu.gameserver.model.creature.player.enums.EGenderType;
import com.mongodb.BasicDBObject;

public abstract class WriteCharacterInfo extends WriteItemInfo {
    protected void writeAppearanceData(final SendByteBuffer buffer, final Player player) {
        final AppearanceFaceHolder face = player.getPlayerAppearance().getFace();
        final AppearanceHairHolder hairs = player.getPlayerAppearance().getHairs();
        final AppearanceBodyHolder body = player.getPlayerAppearance().getBody();
        final AppearanceTattooHolder tattoo = player.getPlayerAppearance().getTattoo();
        buffer.writeC(face.getChinDeformation().getPositionX());
        buffer.writeC(face.getChinDeformation().getPositionY());
        buffer.writeC(face.getChinDeformation().getPositionZ());
        buffer.writeC(face.getChinDeformation().getRotationX());
        buffer.writeC(face.getChinDeformation().getRotationY());
        buffer.writeC(face.getChinDeformation().getRotationZ());
        buffer.writeC(face.getChinDeformation().getStretchX());
        buffer.writeC(face.getChinDeformation().getStretchY());
        buffer.writeC(face.getChinDeformation().getStretchZ());
        buffer.writeC(face.getChin().getPositionX());
        buffer.writeC(face.getChin().getPositionY());
        buffer.writeC(face.getChin().getPositionZ());
        buffer.writeC(face.getChin().getRotationX());
        buffer.writeC(face.getChin().getRotationY());
        buffer.writeC(face.getChin().getRotationZ());
        buffer.writeC(face.getChin().getStretchX());
        buffer.writeC(face.getChin().getStretchY());
        buffer.writeC(face.getChin().getStretchZ());
        buffer.writeC(face.getSkullLeft().getPositionX());
        buffer.writeC(face.getSkullLeft().getPositionY());
        buffer.writeC(face.getSkullLeft().getPositionZ());
        buffer.writeC(face.getSkullLeft().getRotationX());
        buffer.writeC(face.getSkullLeft().getRotationY());
        buffer.writeC(face.getSkullLeft().getRotationZ());
        buffer.writeC(face.getSkullLeft().getStretchX());
        buffer.writeC(face.getSkullLeft().getStretchY());
        buffer.writeC(face.getSkullLeft().getStretchZ());
        buffer.writeC(face.getSkullRight().getPositionX());
        buffer.writeC(face.getSkullRight().getPositionY());
        buffer.writeC(face.getSkullRight().getPositionZ());
        buffer.writeC(face.getSkullRight().getRotationX());
        buffer.writeC(face.getSkullRight().getRotationY());
        buffer.writeC(face.getSkullRight().getRotationZ());
        buffer.writeC(face.getSkullRight().getStretchX());
        buffer.writeC(face.getSkullRight().getStretchY());
        buffer.writeC(face.getSkullRight().getStretchZ());
        buffer.writeC(face.getSkull2Left().getPositionX());
        buffer.writeC(face.getSkull2Left().getPositionY());
        buffer.writeC(face.getSkull2Left().getPositionZ());
        buffer.writeC(face.getSkull2Left().getRotationX());
        buffer.writeC(face.getSkull2Left().getRotationY());
        buffer.writeC(face.getSkull2Left().getRotationZ());
        buffer.writeC(face.getSkull2Left().getStretchX());
        buffer.writeC(face.getSkull2Left().getStretchY());
        buffer.writeC(face.getSkull2Left().getStretchZ());
        buffer.writeC(face.getSkull2Right().getPositionX());
        buffer.writeC(face.getSkull2Right().getPositionY());
        buffer.writeC(face.getSkull2Right().getPositionZ());
        buffer.writeC(face.getSkull2Right().getRotationX());
        buffer.writeC(face.getSkull2Right().getRotationY());
        buffer.writeC(face.getSkull2Right().getRotationZ());
        buffer.writeC(face.getSkull2Right().getStretchX());
        buffer.writeC(face.getSkull2Right().getStretchY());
        buffer.writeC(face.getSkull2Right().getStretchZ());
        buffer.writeC(face.getSkull3Left().getPositionX());
        buffer.writeC(face.getSkull3Left().getPositionY());
        buffer.writeC(face.getSkull3Left().getPositionZ());
        buffer.writeC(face.getSkull3Left().getRotationX());
        buffer.writeC(face.getSkull3Left().getRotationY());
        buffer.writeC(face.getSkull3Left().getRotationZ());
        buffer.writeC(face.getSkull3Left().getStretchX());
        buffer.writeC(face.getSkull3Left().getStretchY());
        buffer.writeC(face.getSkull3Left().getStretchZ());
        buffer.writeC(face.getSkull3Right().getPositionX());
        buffer.writeC(face.getSkull3Right().getPositionY());
        buffer.writeC(face.getSkull3Right().getPositionZ());
        buffer.writeC(face.getSkull3Right().getRotationX());
        buffer.writeC(face.getSkull3Right().getRotationY());
        buffer.writeC(face.getSkull3Right().getRotationZ());
        buffer.writeC(face.getSkull3Right().getStretchX());
        buffer.writeC(face.getSkull3Right().getStretchY());
        buffer.writeC(face.getSkull3Right().getStretchZ());
        buffer.writeC(face.getEarLeft().getPositionX());
        buffer.writeC(face.getEarLeft().getPositionY());
        buffer.writeC(face.getEarLeft().getPositionZ());
        buffer.writeC(face.getEarLeft().getRotationX());
        buffer.writeC(face.getEarLeft().getRotationY());
        buffer.writeC(face.getEarLeft().getRotationZ());
        buffer.writeC(face.getEarLeft().getStretchX());
        buffer.writeC(face.getEarLeft().getStretchY());
        buffer.writeC(face.getEarLeft().getStretchZ());
        buffer.writeC(face.getEarRight().getPositionX());
        buffer.writeC(face.getEarRight().getPositionY());
        buffer.writeC(face.getEarRight().getPositionZ());
        buffer.writeC(face.getEarRight().getRotationX());
        buffer.writeC(face.getEarRight().getRotationY());
        buffer.writeC(face.getEarRight().getRotationZ());
        buffer.writeC(face.getEarRight().getStretchX());
        buffer.writeC(face.getEarRight().getStretchY());
        buffer.writeC(face.getEarRight().getStretchZ());
        buffer.writeC(face.getEarLobes().getPositionX());
        buffer.writeC(face.getEarLobes().getPositionY());
        buffer.writeC(face.getEarLobes().getPositionZ());
        buffer.writeC(face.getEarLobes().getRotationX());
        buffer.writeC(face.getEarLobes().getRotationY());
        buffer.writeC(face.getEarLobes().getRotationZ());
        buffer.writeC(face.getEarLobes().getStretchX());
        buffer.writeC(face.getEarLobes().getStretchY());
        buffer.writeC(face.getEarLobes().getStretchZ());
        buffer.writeC(face.getBrow().getPositionX());
        buffer.writeC(face.getBrow().getPositionY());
        buffer.writeC(face.getBrow().getPositionZ());
        buffer.writeC(face.getBrow().getRotationX());
        buffer.writeC(face.getBrow().getRotationY());
        buffer.writeC(face.getBrow().getRotationZ());
        buffer.writeC(face.getBrow().getStretchX());
        buffer.writeC(face.getBrow().getStretchY());
        buffer.writeC(face.getBrow().getStretchZ());
        buffer.writeC(face.getEyebrowLeft().getPositionX());
        buffer.writeC(face.getEyebrowLeft().getPositionY());
        buffer.writeC(face.getEyebrowLeft().getPositionZ());
        buffer.writeC(face.getEyebrowLeft().getRotationX());
        buffer.writeC(face.getEyebrowLeft().getRotationY());
        buffer.writeC(face.getEyebrowLeft().getRotationZ());
        buffer.writeC(face.getEyebrowLeft().getStretchX());
        buffer.writeC(face.getEyebrowLeft().getStretchY());
        buffer.writeC(face.getEyebrowLeft().getStretchZ());
        buffer.writeC(face.getEyebrowRight().getPositionX());
        buffer.writeC(face.getEyebrowRight().getPositionY());
        buffer.writeC(face.getEyebrowRight().getPositionZ());
        buffer.writeC(face.getEyebrowRight().getRotationX());
        buffer.writeC(face.getEyebrowRight().getRotationY());
        buffer.writeC(face.getEyebrowRight().getRotationZ());
        buffer.writeC(face.getEyebrowRight().getStretchX());
        buffer.writeC(face.getEyebrowRight().getStretchY());
        buffer.writeC(face.getEyebrowRight().getStretchZ());
        buffer.writeC(face.getNoseBridgeUp().getPositionX());
        buffer.writeC(face.getNoseBridgeUp().getPositionY());
        buffer.writeC(face.getNoseBridgeUp().getPositionZ());
        buffer.writeC(face.getNoseBridgeUp().getRotationX());
        buffer.writeC(face.getNoseBridgeUp().getRotationY());
        buffer.writeC(face.getNoseBridgeUp().getRotationZ());
        buffer.writeC(face.getNoseBridgeUp().getStretchX());
        buffer.writeC(face.getNoseBridgeUp().getStretchY());
        buffer.writeC(face.getNoseBridgeUp().getStretchZ());
        buffer.writeC(face.getEyebrowLeft2().getPositionX());
        buffer.writeC(face.getEyebrowLeft2().getPositionY());
        buffer.writeC(face.getEyebrowLeft2().getPositionZ());
        buffer.writeC(face.getEyebrowLeft2().getRotationX());
        buffer.writeC(face.getEyebrowLeft2().getRotationY());
        buffer.writeC(face.getEyebrowLeft2().getRotationZ());
        buffer.writeC(face.getEyebrowLeft2().getStretchX());
        buffer.writeC(face.getEyebrowLeft2().getStretchY());
        buffer.writeC(face.getEyebrowLeft2().getStretchZ());
        buffer.writeC(face.getEyebrowRight2().getPositionX());
        buffer.writeC(face.getEyebrowRight2().getPositionY());
        buffer.writeC(face.getEyebrowRight2().getPositionZ());
        buffer.writeC(face.getEyebrowRight2().getRotationX());
        buffer.writeC(face.getEyebrowRight2().getRotationY());
        buffer.writeC(face.getEyebrowRight2().getRotationZ());
        buffer.writeC(face.getEyebrowRight2().getStretchX());
        buffer.writeC(face.getEyebrowRight2().getStretchY());
        buffer.writeC(face.getEyebrowRight2().getStretchZ());
        buffer.writeC(face.getEyelidDownLeft().getPositionX());
        buffer.writeC(face.getEyelidDownLeft().getPositionY());
        buffer.writeC(face.getEyelidDownLeft().getPositionZ());
        buffer.writeC(face.getEyelidDownLeft().getRotationX());
        buffer.writeC(face.getEyelidDownLeft().getRotationY());
        buffer.writeC(face.getEyelidDownLeft().getRotationZ());
        buffer.writeC(face.getEyelidDownLeft().getStretchX());
        buffer.writeC(face.getEyelidDownLeft().getStretchY());
        buffer.writeC(face.getEyelidDownLeft().getStretchZ());
        buffer.writeC(face.getEyelidDownRight().getPositionX());
        buffer.writeC(face.getEyelidDownRight().getPositionY());
        buffer.writeC(face.getEyelidDownRight().getPositionZ());
        buffer.writeC(face.getEyelidDownRight().getRotationX());
        buffer.writeC(face.getEyelidDownRight().getRotationY());
        buffer.writeC(face.getEyelidDownRight().getRotationZ());
        buffer.writeC(face.getEyelidDownRight().getStretchX());
        buffer.writeC(face.getEyelidDownRight().getStretchY());
        buffer.writeC(face.getEyelidDownRight().getStretchZ());
        buffer.writeC(face.getEyeCornerRight().getPositionX());
        buffer.writeC(face.getEyeCornerRight().getPositionY());
        buffer.writeC(face.getEyeCornerRight().getPositionZ());
        buffer.writeC(face.getEyeCornerRight().getRotationX());
        buffer.writeC(face.getEyeCornerRight().getRotationY());
        buffer.writeC(face.getEyeCornerRight().getRotationZ());
        buffer.writeC(face.getEyeCornerRight().getStretchX());
        buffer.writeC(face.getEyeCornerRight().getStretchY());
        buffer.writeC(face.getEyeCornerRight().getStretchZ());
        buffer.writeC(face.getEyeCorner2Left().getPositionX());
        buffer.writeC(face.getEyeCorner2Left().getPositionY());
        buffer.writeC(face.getEyeCorner2Left().getPositionZ());
        buffer.writeC(face.getEyeCorner2Left().getRotationX());
        buffer.writeC(face.getEyeCorner2Left().getRotationY());
        buffer.writeC(face.getEyeCorner2Left().getRotationZ());
        buffer.writeC(face.getEyeCorner2Left().getStretchX());
        buffer.writeC(face.getEyeCorner2Left().getStretchY());
        buffer.writeC(face.getEyeCorner2Left().getStretchZ());
        buffer.writeC(face.getEyelidUpLeft().getPositionX());
        buffer.writeC(face.getEyelidUpLeft().getPositionY());
        buffer.writeC(face.getEyelidUpLeft().getPositionZ());
        buffer.writeC(face.getEyelidUpLeft().getRotationX());
        buffer.writeC(face.getEyelidUpLeft().getRotationY());
        buffer.writeC(face.getEyelidUpLeft().getRotationZ());
        buffer.writeC(face.getEyelidUpLeft().getStretchX());
        buffer.writeC(face.getEyelidUpLeft().getStretchY());
        buffer.writeC(face.getEyelidUpLeft().getStretchZ());
        buffer.writeC(face.getEyelidUpRight().getPositionX());
        buffer.writeC(face.getEyelidUpRight().getPositionY());
        buffer.writeC(face.getEyelidUpRight().getPositionZ());
        buffer.writeC(face.getEyelidUpRight().getRotationX());
        buffer.writeC(face.getEyelidUpRight().getRotationY());
        buffer.writeC(face.getEyelidUpRight().getRotationZ());
        buffer.writeC(face.getEyelidUpRight().getStretchX());
        buffer.writeC(face.getEyelidUpRight().getStretchY());
        buffer.writeC(face.getEyelidUpRight().getStretchZ());
        buffer.writeC(face.getEyeCorner2Right().getPositionX());
        buffer.writeC(face.getEyeCorner2Right().getPositionY());
        buffer.writeC(face.getEyeCorner2Right().getPositionZ());
        buffer.writeC(face.getEyeCorner2Right().getRotationX());
        buffer.writeC(face.getEyeCorner2Right().getRotationY());
        buffer.writeC(face.getEyeCorner2Right().getRotationZ());
        buffer.writeC(face.getEyeCorner2Right().getStretchX());
        buffer.writeC(face.getEyeCorner2Right().getStretchY());
        buffer.writeC(face.getEyeCorner2Right().getStretchZ());
        buffer.writeC(face.getEyeCornerLeft().getPositionX());
        buffer.writeC(face.getEyeCornerLeft().getPositionY());
        buffer.writeC(face.getEyeCornerLeft().getPositionZ());
        buffer.writeC(face.getEyeCornerLeft().getRotationX());
        buffer.writeC(face.getEyeCornerLeft().getRotationY());
        buffer.writeC(face.getEyeCornerLeft().getRotationZ());
        buffer.writeC(face.getEyeCornerLeft().getStretchX());
        buffer.writeC(face.getEyeCornerLeft().getStretchY());
        buffer.writeC(face.getEyeCornerLeft().getStretchZ());
        buffer.writeC(face.getEyeLeft().getPositionX());
        buffer.writeC(face.getEyeLeft().getPositionY());
        buffer.writeC(face.getEyeLeft().getPositionZ());
        buffer.writeC(face.getEyeLeft().getRotationX());
        buffer.writeC(face.getEyeLeft().getRotationY());
        buffer.writeC(face.getEyeLeft().getRotationZ());
        buffer.writeC(face.getEyeLeft().getStretchX());
        buffer.writeC(face.getEyeLeft().getStretchY());
        buffer.writeC(face.getEyeLeft().getStretchZ());
        buffer.writeC(face.getEyeRight().getPositionX());
        buffer.writeC(face.getEyeRight().getPositionY());
        buffer.writeC(face.getEyeRight().getPositionZ());
        buffer.writeC(face.getEyeRight().getRotationX());
        buffer.writeC(face.getEyeRight().getRotationY());
        buffer.writeC(face.getEyeRight().getRotationZ());
        buffer.writeC(face.getEyeRight().getStretchX());
        buffer.writeC(face.getEyeRight().getStretchY());
        buffer.writeC(face.getEyeRight().getStretchZ());
        buffer.writeC(face.getCheekCrownLeft().getPositionX());
        buffer.writeC(face.getCheekCrownLeft().getPositionY());
        buffer.writeC(face.getCheekCrownLeft().getPositionZ());
        buffer.writeC(face.getCheekCrownLeft().getRotationX());
        buffer.writeC(face.getCheekCrownLeft().getRotationY());
        buffer.writeC(face.getCheekCrownLeft().getRotationZ());
        buffer.writeC(face.getCheekCrownLeft().getStretchX());
        buffer.writeC(face.getCheekCrownLeft().getStretchY());
        buffer.writeC(face.getCheekCrownLeft().getStretchZ());
        buffer.writeC(face.getCheekCrownRight().getPositionX());
        buffer.writeC(face.getCheekCrownRight().getPositionY());
        buffer.writeC(face.getCheekCrownRight().getPositionZ());
        buffer.writeC(face.getCheekCrownRight().getRotationX());
        buffer.writeC(face.getCheekCrownRight().getRotationY());
        buffer.writeC(face.getCheekCrownRight().getRotationZ());
        buffer.writeC(face.getCheekCrownRight().getStretchX());
        buffer.writeC(face.getCheekCrownRight().getStretchY());
        buffer.writeC(face.getCheekCrownRight().getStretchZ());
        buffer.writeC(face.getNoseCheekLeft().getPositionX());
        buffer.writeC(face.getNoseCheekLeft().getPositionY());
        buffer.writeC(face.getNoseCheekLeft().getPositionZ());
        buffer.writeC(face.getNoseCheekLeft().getRotationX());
        buffer.writeC(face.getNoseCheekLeft().getRotationY());
        buffer.writeC(face.getNoseCheekLeft().getRotationZ());
        buffer.writeC(face.getNoseCheekLeft().getStretchX());
        buffer.writeC(face.getNoseCheekLeft().getStretchY());
        buffer.writeC(face.getNoseCheekLeft().getStretchZ());
        buffer.writeC(face.getNoseCheekRight().getPositionX());
        buffer.writeC(face.getNoseCheekRight().getPositionY());
        buffer.writeC(face.getNoseCheekRight().getPositionZ());
        buffer.writeC(face.getNoseCheekRight().getRotationX());
        buffer.writeC(face.getNoseCheekRight().getRotationY());
        buffer.writeC(face.getNoseCheekRight().getRotationZ());
        buffer.writeC(face.getNoseCheekRight().getStretchX());
        buffer.writeC(face.getNoseCheekRight().getStretchY());
        buffer.writeC(face.getNoseCheekRight().getStretchZ());
        buffer.writeC(face.getNose().getPositionX());
        buffer.writeC(face.getNose().getPositionY());
        buffer.writeC(face.getNose().getPositionZ());
        buffer.writeC(face.getNose().getRotationX());
        buffer.writeC(face.getNose().getRotationY());
        buffer.writeC(face.getNose().getRotationZ());
        buffer.writeC(face.getNose().getStretchX());
        buffer.writeC(face.getNose().getStretchY());
        buffer.writeC(face.getNose().getStretchZ());
        buffer.writeC(face.getNoseCheek2Left().getPositionX());
        buffer.writeC(face.getNoseCheek2Left().getPositionY());
        buffer.writeC(face.getNoseCheek2Left().getPositionZ());
        buffer.writeC(face.getNoseCheek2Left().getRotationX());
        buffer.writeC(face.getNoseCheek2Left().getRotationY());
        buffer.writeC(face.getNoseCheek2Left().getRotationZ());
        buffer.writeC(face.getNoseCheek2Left().getStretchX());
        buffer.writeC(face.getNoseCheek2Left().getStretchY());
        buffer.writeC(face.getNoseCheek2Left().getStretchZ());
        buffer.writeC(face.getNoseCheek2Right().getPositionX());
        buffer.writeC(face.getNoseCheek2Right().getPositionY());
        buffer.writeC(face.getNoseCheek2Right().getPositionZ());
        buffer.writeC(face.getNoseCheek2Right().getRotationX());
        buffer.writeC(face.getNoseCheek2Right().getRotationY());
        buffer.writeC(face.getNoseCheek2Right().getRotationZ());
        buffer.writeC(face.getNoseCheek2Right().getStretchX());
        buffer.writeC(face.getNoseCheek2Right().getStretchY());
        buffer.writeC(face.getNoseCheek2Right().getStretchZ());
        buffer.writeC(face.getNoseBridge().getPositionX());
        buffer.writeC(face.getNoseBridge().getPositionY());
        buffer.writeC(face.getNoseBridge().getPositionZ());
        buffer.writeC(face.getNoseBridge().getRotationX());
        buffer.writeC(face.getNoseBridge().getRotationY());
        buffer.writeC(face.getNoseBridge().getRotationZ());
        buffer.writeC(face.getNoseBridge().getStretchX());
        buffer.writeC(face.getNoseBridge().getStretchY());
        buffer.writeC(face.getNoseBridge().getStretchZ());
        buffer.writeC(face.getLipCenterUp().getPositionX());
        buffer.writeC(face.getLipCenterUp().getPositionY());
        buffer.writeC(face.getLipCenterUp().getPositionZ());
        buffer.writeC(face.getLipCenterUp().getRotationX());
        buffer.writeC(face.getLipCenterUp().getRotationY());
        buffer.writeC(face.getLipCenterUp().getRotationZ());
        buffer.writeC(face.getLipCenterUp().getStretchX());
        buffer.writeC(face.getLipCenterUp().getStretchY());
        buffer.writeC(face.getLipCenterUp().getStretchZ());
        buffer.writeC(face.getLipSideUpLeft().getPositionX());
        buffer.writeC(face.getLipSideUpLeft().getPositionY());
        buffer.writeC(face.getLipSideUpLeft().getPositionZ());
        buffer.writeC(face.getLipSideUpLeft().getRotationX());
        buffer.writeC(face.getLipSideUpLeft().getRotationY());
        buffer.writeC(face.getLipSideUpLeft().getRotationZ());
        buffer.writeC(face.getLipSideUpLeft().getStretchX());
        buffer.writeC(face.getLipSideUpLeft().getStretchY());
        buffer.writeC(face.getLipSideUpLeft().getStretchZ());
        buffer.writeC(face.getLipSideUpRight().getPositionX());
        buffer.writeC(face.getLipSideUpRight().getPositionY());
        buffer.writeC(face.getLipSideUpRight().getPositionZ());
        buffer.writeC(face.getLipSideUpRight().getRotationX());
        buffer.writeC(face.getLipSideUpRight().getRotationY());
        buffer.writeC(face.getLipSideUpRight().getRotationZ());
        buffer.writeC(face.getLipSideUpRight().getStretchX());
        buffer.writeC(face.getLipSideUpRight().getStretchY());
        buffer.writeC(face.getLipSideUpRight().getStretchZ());
        buffer.writeC(face.getLipSide2UpLeft().getPositionX());
        buffer.writeC(face.getLipSide2UpLeft().getPositionY());
        buffer.writeC(face.getLipSide2UpLeft().getPositionZ());
        buffer.writeC(face.getLipSide2UpLeft().getRotationX());
        buffer.writeC(face.getLipSide2UpLeft().getRotationY());
        buffer.writeC(face.getLipSide2UpLeft().getRotationZ());
        buffer.writeC(face.getLipSide2UpLeft().getStretchX());
        buffer.writeC(face.getLipSide2UpLeft().getStretchY());
        buffer.writeC(face.getLipSide2UpLeft().getStretchZ());
        buffer.writeC(face.getLipSide2UpRight().getPositionX());
        buffer.writeC(face.getLipSide2UpRight().getPositionY());
        buffer.writeC(face.getLipSide2UpRight().getPositionZ());
        buffer.writeC(face.getLipSide2UpRight().getRotationX());
        buffer.writeC(face.getLipSide2UpRight().getRotationY());
        buffer.writeC(face.getLipSide2UpRight().getRotationZ());
        buffer.writeC(face.getLipSide2UpRight().getStretchX());
        buffer.writeC(face.getLipSide2UpRight().getStretchY());
        buffer.writeC(face.getLipSide2UpRight().getStretchZ());
        buffer.writeC(face.getLipSideDownLeft().getPositionX());
        buffer.writeC(face.getLipSideDownLeft().getPositionY());
        buffer.writeC(face.getLipSideDownLeft().getPositionZ());
        buffer.writeC(face.getLipSideDownLeft().getRotationX());
        buffer.writeC(face.getLipSideDownLeft().getRotationY());
        buffer.writeC(face.getLipSideDownLeft().getRotationZ());
        buffer.writeC(face.getLipSideDownLeft().getStretchX());
        buffer.writeC(face.getLipSideDownLeft().getStretchY());
        buffer.writeC(face.getLipSideDownLeft().getStretchZ());
        buffer.writeC(face.getLipSideDownRight().getPositionX());
        buffer.writeC(face.getLipSideDownRight().getPositionY());
        buffer.writeC(face.getLipSideDownRight().getPositionZ());
        buffer.writeC(face.getLipSideDownRight().getRotationX());
        buffer.writeC(face.getLipSideDownRight().getRotationY());
        buffer.writeC(face.getLipSideDownRight().getRotationZ());
        buffer.writeC(face.getLipSideDownRight().getStretchX());
        buffer.writeC(face.getLipSideDownRight().getStretchY());
        buffer.writeC(face.getLipSideDownRight().getStretchZ());
        buffer.writeC(face.getLipCenterDown().getPositionX());
        buffer.writeC(face.getLipCenterDown().getPositionY());
        buffer.writeC(face.getLipCenterDown().getPositionZ());
        buffer.writeC(face.getLipCenterDown().getRotationX());
        buffer.writeC(face.getLipCenterDown().getRotationY());
        buffer.writeC(face.getLipCenterDown().getRotationZ());
        buffer.writeC(face.getLipCenterDown().getStretchX());
        buffer.writeC(face.getLipCenterDown().getStretchY());
        buffer.writeC(face.getLipCenterDown().getStretchZ());
        buffer.writeC(0);
        buffer.writeC(body.getHeight());
        buffer.writeC(0);
        buffer.writeC(body.getCalvesLeft().getStretchX());
        buffer.writeC(body.getCalvesLeft().getStretchY());
        buffer.writeC(body.getCalvesLeft().getStretchZ());
        buffer.writeC(body.getCalvesRight().getStretchX());
        buffer.writeC(body.getCalvesRight().getStretchY());
        buffer.writeC(body.getCalvesRight().getStretchZ());
        buffer.writeC(body.getThighLeft().getStretchX());
        buffer.writeC(body.getThighLeft().getStretchY());
        buffer.writeC(body.getThighLeft().getStretchZ());
        buffer.writeC(body.getThighRight().getStretchX());
        buffer.writeC(body.getThighRight().getStretchY());
        buffer.writeC(body.getThighRight().getStretchZ());
        buffer.writeC(body.getFootLeft().getStretchX());
        buffer.writeC(body.getFootLeft().getStretchY());
        buffer.writeC(body.getFootLeft().getStretchZ());
        buffer.writeC(body.getFootRight().getStretchX());
        buffer.writeC(body.getFootRight().getStretchY());
        buffer.writeC(body.getFootRight().getStretchZ());
        buffer.writeC(body.getNeck().getStretchX());
        buffer.writeC(body.getNeck().getStretchY());
        buffer.writeC(body.getNeck().getStretchZ());
        buffer.writeC(body.getGroin().getStretchX());
        buffer.writeC(body.getGroin().getStretchY());
        buffer.writeC(body.getGroin().getStretchZ());
        buffer.writeC(body.getStomach().getStretchX());
        buffer.writeC(body.getStomach().getStretchY());
        buffer.writeC(body.getStomach().getStretchZ());
        buffer.writeC(body.getChest().getStretchX());
        buffer.writeC(body.getChest().getStretchY());
        buffer.writeC(body.getChest().getStretchZ());
        buffer.writeC(body.getBreast().getStretchX());
        buffer.writeC(body.getBreast().getStretchY());
        buffer.writeC(body.getBreast().getStretchZ());
        buffer.writeC(body.getButtockLeft().getStretchX());
        buffer.writeC(body.getButtockLeft().getStretchY());
        buffer.writeC(body.getButtockLeft().getStretchZ());
        buffer.writeC(body.getButtockRight().getStretchX());
        buffer.writeC(body.getButtockRight().getStretchY());
        buffer.writeC(body.getButtockRight().getStretchZ());
        buffer.writeC(body.getShouldersLeft().getStretchX());
        buffer.writeC(body.getShouldersLeft().getStretchY());
        buffer.writeC(body.getShouldersLeft().getStretchZ());
        buffer.writeC(body.getShouldersRight().getStretchX());
        buffer.writeC(body.getShouldersRight().getStretchY());
        buffer.writeC(body.getShouldersRight().getStretchZ());
        buffer.writeC(body.getForearmLeft().getStretchX());
        buffer.writeC(body.getForearmLeft().getStretchY());
        buffer.writeC(body.getForearmLeft().getStretchZ());
        buffer.writeC(body.getForearmRight().getStretchX());
        buffer.writeC(body.getForearmRight().getStretchY());
        buffer.writeC(body.getForearmRight().getStretchZ());
        buffer.writeC(body.getArmLeft().getStretchX());
        buffer.writeC(body.getArmLeft().getStretchY());
        buffer.writeC(body.getArmLeft().getStretchZ());
        buffer.writeC(body.getArmRight().getStretchX());
        buffer.writeC(body.getArmRight().getStretchY());
        buffer.writeC(body.getArmRight().getStretchZ());
        buffer.writeC(body.getHandLeft().getStretchX());
        buffer.writeC(body.getHandLeft().getStretchY());
        buffer.writeC(body.getHandLeft().getStretchZ());
        buffer.writeC(body.getHandRight().getStretchX());
        buffer.writeC(body.getHandRight().getStretchY());
        buffer.writeC(body.getHandRight().getStretchZ());
        buffer.writeB(body.getAdditionalSizeData());
        buffer.writeB(hairs.getAdditionalSizeData());
        buffer.writeC(tattoo.getFaceTattooId());
        buffer.writeC(tattoo.getBodyTattooId());
        buffer.writeC(hairs.getLength());
        buffer.writeC(hairs.getBackLength());
        buffer.writeC(hairs.getSideLength());
        buffer.writeC(hairs.getCurls());
        buffer.writeC(hairs.getSwirls());
        buffer.writeC(hairs.getShine());
        buffer.writeC(hairs.getColorId());
        buffer.writeC(hairs.getTipsSaturation());
        buffer.writeC(hairs.getTipsLength());
        buffer.writeC(hairs.getTipsColorId());
        buffer.writeC(hairs.getRootsSaturation());
        buffer.writeC(hairs.getRootsLength());
        buffer.writeC(hairs.getRootsColorId());
        buffer.writeC(face.getColorId());
        buffer.writeC(face.getShine());
        if (player.getClassType().getGenderType() == EGenderType.Woman) {
            buffer.writeC(face.getEyeMakeUp().getId());
            buffer.writeC(face.getEyeMakeUp().getDensity());
            buffer.writeC(face.getEyeMakeUp().getHighlight());
            buffer.writeC(face.getEyeMakeUp().getShine());
            buffer.writeC(face.getEyeMakeUp().getArea());
            buffer.writeC(face.getEyeMakeUp().getColorId());
            buffer.writeC(face.getEyebrowsMakeUp().getId());
            buffer.writeC(face.getEyebrowsMakeUp().getDensity());
            buffer.writeC(face.getEyebrowsMakeUp().getHighlight());
            buffer.writeC(face.getEyebrowsMakeUp().getShine());
            buffer.writeC(face.getEyebrowsMakeUp().getArea());
            buffer.writeC(face.getEyebrowsMakeUp().getColorId());
            buffer.writeC(face.getRougeMakeUp().getId());
            buffer.writeC(face.getRougeMakeUp().getDensity());
            buffer.writeC(face.getRougeMakeUp().getHighlight());
            buffer.writeC(face.getRougeMakeUp().getShine());
            buffer.writeC(face.getRougeMakeUp().getArea());
            buffer.writeC(face.getRougeMakeUp().getColorId());
            buffer.writeC(face.getLipsMakeUp().getId());
            buffer.writeC(face.getLipsMakeUp().getDensity());
            buffer.writeC(face.getLipsMakeUp().getHighlight());
            buffer.writeC(face.getLipsMakeUp().getShine());
            buffer.writeC(face.getLipsMakeUp().getArea());
            buffer.writeC(face.getLipsMakeUp().getColorId());
            buffer.writeC(tattoo.getFaceTattooX());
            buffer.writeC(tattoo.getFaceTattooY());
            buffer.writeC(tattoo.getFaceTattooRotation());
            buffer.writeC(tattoo.getFaceTattooWidth());
            buffer.writeC(tattoo.getFaceTattooHeight());
            buffer.writeC(tattoo.getFaceTattooDensity());
            buffer.writeC(tattoo.getFaceTattooShine());
            buffer.writeC(tattoo.getFaceTattooColorId());
            buffer.writeC(face.getWrinklesBrow());
            buffer.writeC(face.getWrinklesEyes());
            buffer.writeC(face.getWrinklesLips());
            buffer.writeC(face.getEyelashesMakeUp().getId());
            buffer.writeC(face.getEyelashesMakeUp().getLength());
            buffer.writeC(face.getEyelashesMakeUp().getColorId());
            buffer.writeC(face.getEyeShadowsMakeUp().getId());
            buffer.writeC(face.getEyeShadowsMakeUp().getLength());
            buffer.writeC(face.getEyeShadowsMakeUp().getColorId());
            buffer.writeC(face.getEyelinerMakeUp().getId());
            buffer.writeC(face.getEyelinerMakeUp().getLength());
            buffer.writeC(face.getEyelinerMakeUp().getColorId());
            buffer.writeC(face.getLeftEyePupil().getId());
            buffer.writeC(face.getLeftEyePupil().getPurity());
            buffer.writeC(face.getLeftEyePupil().getSize());
            buffer.writeC(face.getLeftEyePupil().getWidth());
            buffer.writeC(face.getLeftEyePupil().getArea());
            buffer.writeC(face.getLeftEyePupil().getColorId());
            buffer.writeC(face.getLeftEyeIris().getId());
            buffer.writeC(face.getLeftEyeIris().getPurity());
            buffer.writeC(face.getLeftEyeIris().getSize());
            buffer.writeC(face.getLeftEyeIris().getWidth());
            buffer.writeC(face.getLeftEyeIris().getArea());
            buffer.writeC(face.getLeftEyeIris().getColorId());
            buffer.writeC(face.getLeftEyeLenses().getId());
            buffer.writeC(face.getLeftEyeLenses().getPurity());
            buffer.writeC(face.getLeftEyeLenses().getHeight());
            buffer.writeC(face.getLeftEyeLenses().getHighlight());
            buffer.writeC(face.getLeftEyeLenses().getShine());
            buffer.writeC(face.getLeftEyeLenses().getColorId());
            buffer.writeC(face.getRightEyePupil().getId());
            buffer.writeC(face.getRightEyePupil().getPurity());
            buffer.writeC(face.getRightEyePupil().getSize());
            buffer.writeC(face.getRightEyePupil().getWidth());
            buffer.writeC(face.getRightEyePupil().getArea());
            buffer.writeC(face.getRightEyePupil().getColorId());
            buffer.writeC(face.getRightEyeIris().getId());
            buffer.writeC(face.getRightEyeIris().getPurity());
            buffer.writeC(face.getRightEyeIris().getSize());
            buffer.writeC(face.getRightEyeIris().getWidth());
            buffer.writeC(face.getRightEyeIris().getArea());
            buffer.writeC(face.getRightEyeIris().getColorId());
            buffer.writeC(face.getRightEyeLenses().getId());
            buffer.writeC(face.getRightEyeLenses().getPurity());
            buffer.writeC(face.getRightEyeLenses().getHeight());
            buffer.writeC(face.getRightEyeLenses().getHighlight());
            buffer.writeC(face.getRightEyeLenses().getShine());
            buffer.writeC(face.getRightEyeLenses().getColorId());
            buffer.writeC(body.getChestMuscles());
            buffer.writeC(body.getArmsMuscles());
            buffer.writeC(body.getLegsMuscles());
            buffer.writeC(tattoo.getBodyTattooX());
            buffer.writeC(tattoo.getBodyTattooY());
            buffer.writeC(tattoo.getBodyTattooRotation());
            buffer.writeC(tattoo.getBodyTattooWidth());
            buffer.writeC(tattoo.getBodyTattooHeight());
            buffer.writeC(tattoo.getBodyTattooDensity());
            buffer.writeC(tattoo.getBodyTattooShine());
            buffer.writeC(tattoo.getBodyTattooColorId());
            buffer.writeB(new byte[22]);
        } else {
            buffer.writeC(face.getBristle().getId());
            buffer.writeC(face.getBristle().getDensity());
            buffer.writeC(face.getBristle().getShine());
            buffer.writeC(face.getBristle().getArea());
            buffer.writeC(face.getBristle().getColorId());
            buffer.writeC(face.getBeard().getLength());
            buffer.writeC(face.getBeard().getCurls());
            buffer.writeC(face.getBeard().getSwirls());
            buffer.writeC(face.getBeard().getColorId());
            buffer.writeC(face.getMustache().getLength());
            buffer.writeC(face.getMustache().getCurls());
            buffer.writeC(face.getMustache().getSwirls());
            buffer.writeC(face.getMustache().getColorId());
            buffer.writeC(face.getWhiskers().getLength());
            buffer.writeC(face.getWhiskers().getCurls());
            buffer.writeC(face.getWhiskers().getSwirls());
            buffer.writeC(face.getWhiskers().getColorId());
            buffer.writeC(face.getEyebrowsMakeUp().getId());
            buffer.writeC(face.getEyebrowsMakeUp().getDensity());
            buffer.writeC(face.getEyebrowsMakeUp().getHeight());
            buffer.writeC(face.getEyebrowsMakeUp().getShine());
            buffer.writeC(face.getEyebrowsMakeUp().getArea());
            buffer.writeC(face.getEyebrowsMakeUp().getColorId());
            buffer.writeC(face.getEyebrows().getLength());
            buffer.writeC(face.getEyebrows().getCurls());
            buffer.writeC(face.getEyebrows().getSwirls());
            buffer.writeC(face.getEyebrows().getColorId());
            buffer.writeC(face.getEyeMakeUp().getId());
            buffer.writeC(face.getEyeMakeUp().getDensity());
            buffer.writeC(face.getEyeMakeUp().getHighlight());
            buffer.writeC(face.getEyeMakeUp().getShine());
            buffer.writeC(face.getEyeMakeUp().getArea());
            buffer.writeC(face.getEyeMakeUp().getColorId());
            buffer.writeC(face.getLipsMakeUp().getId());
            buffer.writeC(face.getLipsMakeUp().getDensity());
            buffer.writeC(face.getLipsMakeUp().getHighlight());
            buffer.writeC(face.getLipsMakeUp().getShine());
            buffer.writeC(face.getLipsMakeUp().getArea());
            buffer.writeC(face.getLipsMakeUp().getColorId());
            buffer.writeC(tattoo.getFaceTattooX());
            buffer.writeC(tattoo.getFaceTattooY());
            buffer.writeC(tattoo.getFaceTattooRotation());
            buffer.writeC(tattoo.getFaceTattooWidth());
            buffer.writeC(tattoo.getFaceTattooHeight());
            buffer.writeC(tattoo.getFaceTattooDensity());
            buffer.writeC(tattoo.getFaceTattooShine());
            buffer.writeC(tattoo.getFaceTattooColorId());
            buffer.writeC(face.getWrinklesBrow());
            buffer.writeC(face.getWrinklesEyes());
            buffer.writeC(face.getWrinklesLips());
            buffer.writeC(face.getEyelashesMakeUp().getId());
            buffer.writeC(face.getEyelashesMakeUp().getLength());
            buffer.writeC(face.getEyelashesMakeUp().getColorId());
            buffer.writeC(face.getEyeShadowsMakeUp().getId());
            buffer.writeC(face.getEyeShadowsMakeUp().getLength());
            buffer.writeC(face.getEyeShadowsMakeUp().getColorId());
            buffer.writeC(face.getEyelinerMakeUp().getId());
            buffer.writeC(face.getEyelinerMakeUp().getLength());
            buffer.writeC(face.getEyelinerMakeUp().getColorId());
            buffer.writeC(face.getLeftEyePupil().getId());
            buffer.writeC(face.getLeftEyePupil().getPurity());
            buffer.writeC(face.getLeftEyePupil().getSize());
            buffer.writeC(face.getLeftEyePupil().getWidth());
            buffer.writeC(face.getLeftEyePupil().getArea());
            buffer.writeC(face.getLeftEyePupil().getColorId());
            buffer.writeC(face.getLeftEyeIris().getId());
            buffer.writeC(face.getLeftEyeIris().getPurity());
            buffer.writeC(face.getLeftEyeIris().getSize());
            buffer.writeC(face.getLeftEyeIris().getWidth());
            buffer.writeC(face.getLeftEyeIris().getArea());
            buffer.writeC(face.getLeftEyeIris().getColorId());
            buffer.writeC(face.getLeftEyeLenses().getId());
            buffer.writeC(face.getLeftEyeLenses().getPurity());
            buffer.writeC(face.getLeftEyeLenses().getHeight());
            buffer.writeC(face.getLeftEyeLenses().getHighlight());
            buffer.writeC(face.getLeftEyeLenses().getShine());
            buffer.writeC(face.getLeftEyeLenses().getColorId());
            buffer.writeC(face.getRightEyePupil().getId());
            buffer.writeC(face.getRightEyePupil().getPurity());
            buffer.writeC(face.getRightEyePupil().getSize());
            buffer.writeC(face.getRightEyePupil().getWidth());
            buffer.writeC(face.getRightEyePupil().getArea());
            buffer.writeC(face.getRightEyePupil().getColorId());
            buffer.writeC(face.getRightEyeIris().getId());
            buffer.writeC(face.getRightEyeIris().getPurity());
            buffer.writeC(face.getRightEyeIris().getSize());
            buffer.writeC(face.getRightEyeIris().getWidth());
            buffer.writeC(face.getRightEyeIris().getArea());
            buffer.writeC(face.getRightEyeIris().getColorId());
            buffer.writeC(face.getRightEyeLenses().getId());
            buffer.writeC(face.getRightEyeLenses().getPurity());
            buffer.writeC(face.getRightEyeLenses().getHeight());
            buffer.writeC(face.getRightEyeLenses().getHighlight());
            buffer.writeC(face.getRightEyeLenses().getShine());
            buffer.writeC(face.getRightEyeLenses().getColorId());
            buffer.writeC(body.getChestMuscles());
            buffer.writeC(body.getArmsMuscles());
            buffer.writeC(body.getLegsMuscles());
            buffer.writeC(tattoo.getBodyTattooX());
            buffer.writeC(tattoo.getBodyTattooY());
            buffer.writeC(tattoo.getBodyTattooRotation());
            buffer.writeC(tattoo.getBodyTattooWidth());
            buffer.writeC(tattoo.getBodyTattooHeight());
            buffer.writeC(tattoo.getBodyTattooDensity());
            buffer.writeC(tattoo.getBodyTattooShine());
            buffer.writeC(tattoo.getBodyTattooColorId());
            buffer.writeB(new byte[7]);
        }
        buffer.writeC(face.getIdleAnimationId());
        buffer.writeC(face.getIdleAnimationPower());
        buffer.writeC(1);
        buffer.writeC(0);
        buffer.writeC(0);
        buffer.writeC(0);
        buffer.writeC(player.getPlayerAppearance().getVoicePitch());
        buffer.writeC(0);
        buffer.writeC(0);
        buffer.writeC(0);
        buffer.writeS((CharSequence) player.getFamily(), 62);
    }

    protected void writeAppearanceData(final SendByteBuffer buffer, final BasicDBObject player, final String family) {
        final BasicDBObject playerAppearance = (BasicDBObject) player.get("appearance");
        final BasicDBObject face = (BasicDBObject) playerAppearance.get("face");
        final BasicDBObject hairs = (BasicDBObject) playerAppearance.get("hairs");
        final BasicDBObject body = (BasicDBObject) playerAppearance.get("body");
        final BasicDBObject tattoo = (BasicDBObject) playerAppearance.get("tattoo");
        buffer.writeC(((BasicDBObject) face.get("chinDeformation")).getInt("positionX"));
        buffer.writeC(((BasicDBObject) face.get("chinDeformation")).getInt("positionY"));
        buffer.writeC(((BasicDBObject) face.get("chinDeformation")).getInt("positionZ"));
        buffer.writeC(((BasicDBObject) face.get("chinDeformation")).getInt("rotationX"));
        buffer.writeC(((BasicDBObject) face.get("chinDeformation")).getInt("rotationY"));
        buffer.writeC(((BasicDBObject) face.get("chinDeformation")).getInt("rotationZ"));
        buffer.writeC(((BasicDBObject) face.get("chinDeformation")).getInt("stretchX"));
        buffer.writeC(((BasicDBObject) face.get("chinDeformation")).getInt("stretchY"));
        buffer.writeC(((BasicDBObject) face.get("chinDeformation")).getInt("stretchZ"));
        buffer.writeC(((BasicDBObject) face.get("chin")).getInt("positionX"));
        buffer.writeC(((BasicDBObject) face.get("chin")).getInt("positionY"));
        buffer.writeC(((BasicDBObject) face.get("chin")).getInt("positionZ"));
        buffer.writeC(((BasicDBObject) face.get("chin")).getInt("rotationX"));
        buffer.writeC(((BasicDBObject) face.get("chin")).getInt("rotationY"));
        buffer.writeC(((BasicDBObject) face.get("chin")).getInt("rotationZ"));
        buffer.writeC(((BasicDBObject) face.get("chin")).getInt("stretchX"));
        buffer.writeC(((BasicDBObject) face.get("chin")).getInt("stretchY"));
        buffer.writeC(((BasicDBObject) face.get("chin")).getInt("stretchZ"));
        buffer.writeC(((BasicDBObject) face.get("skullLeft")).getInt("positionX"));
        buffer.writeC(((BasicDBObject) face.get("skullLeft")).getInt("positionY"));
        buffer.writeC(((BasicDBObject) face.get("skullLeft")).getInt("positionZ"));
        buffer.writeC(((BasicDBObject) face.get("skullLeft")).getInt("rotationX"));
        buffer.writeC(((BasicDBObject) face.get("skullLeft")).getInt("rotationY"));
        buffer.writeC(((BasicDBObject) face.get("skullLeft")).getInt("rotationZ"));
        buffer.writeC(((BasicDBObject) face.get("skullLeft")).getInt("stretchX"));
        buffer.writeC(((BasicDBObject) face.get("skullLeft")).getInt("stretchY"));
        buffer.writeC(((BasicDBObject) face.get("skullLeft")).getInt("stretchZ"));
        buffer.writeC(((BasicDBObject) face.get("skullRight")).getInt("positionX"));
        buffer.writeC(((BasicDBObject) face.get("skullRight")).getInt("positionY"));
        buffer.writeC(((BasicDBObject) face.get("skullRight")).getInt("positionZ"));
        buffer.writeC(((BasicDBObject) face.get("skullRight")).getInt("rotationX"));
        buffer.writeC(((BasicDBObject) face.get("skullRight")).getInt("rotationY"));
        buffer.writeC(((BasicDBObject) face.get("skullRight")).getInt("rotationZ"));
        buffer.writeC(((BasicDBObject) face.get("skullRight")).getInt("stretchX"));
        buffer.writeC(((BasicDBObject) face.get("skullRight")).getInt("stretchY"));
        buffer.writeC(((BasicDBObject) face.get("skullRight")).getInt("stretchZ"));
        buffer.writeC(((BasicDBObject) face.get("skull2Left")).getInt("positionX"));
        buffer.writeC(((BasicDBObject) face.get("skull2Left")).getInt("positionY"));
        buffer.writeC(((BasicDBObject) face.get("skull2Left")).getInt("positionZ"));
        buffer.writeC(((BasicDBObject) face.get("skull2Left")).getInt("rotationX"));
        buffer.writeC(((BasicDBObject) face.get("skull2Left")).getInt("rotationY"));
        buffer.writeC(((BasicDBObject) face.get("skull2Left")).getInt("rotationZ"));
        buffer.writeC(((BasicDBObject) face.get("skull2Left")).getInt("stretchX"));
        buffer.writeC(((BasicDBObject) face.get("skull2Left")).getInt("stretchY"));
        buffer.writeC(((BasicDBObject) face.get("skull2Left")).getInt("stretchZ"));
        buffer.writeC(((BasicDBObject) face.get("skull2Right")).getInt("positionX"));
        buffer.writeC(((BasicDBObject) face.get("skull2Right")).getInt("positionY"));
        buffer.writeC(((BasicDBObject) face.get("skull2Right")).getInt("positionZ"));
        buffer.writeC(((BasicDBObject) face.get("skull2Right")).getInt("rotationX"));
        buffer.writeC(((BasicDBObject) face.get("skull2Right")).getInt("rotationY"));
        buffer.writeC(((BasicDBObject) face.get("skull2Right")).getInt("rotationZ"));
        buffer.writeC(((BasicDBObject) face.get("skull2Right")).getInt("stretchX"));
        buffer.writeC(((BasicDBObject) face.get("skull2Right")).getInt("stretchY"));
        buffer.writeC(((BasicDBObject) face.get("skull2Right")).getInt("stretchZ"));
        buffer.writeC(((BasicDBObject) face.get("skull3Left")).getInt("positionX"));
        buffer.writeC(((BasicDBObject) face.get("skull3Left")).getInt("positionY"));
        buffer.writeC(((BasicDBObject) face.get("skull3Left")).getInt("positionZ"));
        buffer.writeC(((BasicDBObject) face.get("skull3Left")).getInt("rotationX"));
        buffer.writeC(((BasicDBObject) face.get("skull3Left")).getInt("rotationY"));
        buffer.writeC(((BasicDBObject) face.get("skull3Left")).getInt("rotationZ"));
        buffer.writeC(((BasicDBObject) face.get("skull3Left")).getInt("stretchX"));
        buffer.writeC(((BasicDBObject) face.get("skull3Left")).getInt("stretchY"));
        buffer.writeC(((BasicDBObject) face.get("skull3Left")).getInt("stretchZ"));
        buffer.writeC(((BasicDBObject) face.get("skull3Right")).getInt("positionX"));
        buffer.writeC(((BasicDBObject) face.get("skull3Right")).getInt("positionY"));
        buffer.writeC(((BasicDBObject) face.get("skull3Right")).getInt("positionZ"));
        buffer.writeC(((BasicDBObject) face.get("skull3Right")).getInt("rotationX"));
        buffer.writeC(((BasicDBObject) face.get("skull3Right")).getInt("rotationY"));
        buffer.writeC(((BasicDBObject) face.get("skull3Right")).getInt("rotationZ"));
        buffer.writeC(((BasicDBObject) face.get("skull3Right")).getInt("stretchX"));
        buffer.writeC(((BasicDBObject) face.get("skull3Right")).getInt("stretchY"));
        buffer.writeC(((BasicDBObject) face.get("skull3Right")).getInt("stretchZ"));
        buffer.writeC(((BasicDBObject) face.get("earLeft")).getInt("positionX"));
        buffer.writeC(((BasicDBObject) face.get("earLeft")).getInt("positionY"));
        buffer.writeC(((BasicDBObject) face.get("earLeft")).getInt("positionZ"));
        buffer.writeC(((BasicDBObject) face.get("earLeft")).getInt("rotationX"));
        buffer.writeC(((BasicDBObject) face.get("earLeft")).getInt("rotationY"));
        buffer.writeC(((BasicDBObject) face.get("earLeft")).getInt("rotationZ"));
        buffer.writeC(((BasicDBObject) face.get("earLeft")).getInt("stretchX"));
        buffer.writeC(((BasicDBObject) face.get("earLeft")).getInt("stretchY"));
        buffer.writeC(((BasicDBObject) face.get("earLeft")).getInt("stretchZ"));
        buffer.writeC(((BasicDBObject) face.get("earRight")).getInt("positionX"));
        buffer.writeC(((BasicDBObject) face.get("earRight")).getInt("positionY"));
        buffer.writeC(((BasicDBObject) face.get("earRight")).getInt("positionZ"));
        buffer.writeC(((BasicDBObject) face.get("earRight")).getInt("rotationX"));
        buffer.writeC(((BasicDBObject) face.get("earRight")).getInt("rotationY"));
        buffer.writeC(((BasicDBObject) face.get("earRight")).getInt("rotationZ"));
        buffer.writeC(((BasicDBObject) face.get("earRight")).getInt("stretchX"));
        buffer.writeC(((BasicDBObject) face.get("earRight")).getInt("stretchY"));
        buffer.writeC(((BasicDBObject) face.get("earRight")).getInt("stretchZ"));
        buffer.writeC(((BasicDBObject) face.get("earLobes")).getInt("positionX"));
        buffer.writeC(((BasicDBObject) face.get("earLobes")).getInt("positionY"));
        buffer.writeC(((BasicDBObject) face.get("earLobes")).getInt("positionZ"));
        buffer.writeC(((BasicDBObject) face.get("earLobes")).getInt("rotationX"));
        buffer.writeC(((BasicDBObject) face.get("earLobes")).getInt("rotationY"));
        buffer.writeC(((BasicDBObject) face.get("earLobes")).getInt("rotationZ"));
        buffer.writeC(((BasicDBObject) face.get("earLobes")).getInt("stretchX"));
        buffer.writeC(((BasicDBObject) face.get("earLobes")).getInt("stretchY"));
        buffer.writeC(((BasicDBObject) face.get("earLobes")).getInt("stretchZ"));
        buffer.writeC(((BasicDBObject) face.get("brow")).getInt("positionX"));
        buffer.writeC(((BasicDBObject) face.get("brow")).getInt("positionY"));
        buffer.writeC(((BasicDBObject) face.get("brow")).getInt("positionZ"));
        buffer.writeC(((BasicDBObject) face.get("brow")).getInt("rotationX"));
        buffer.writeC(((BasicDBObject) face.get("brow")).getInt("rotationY"));
        buffer.writeC(((BasicDBObject) face.get("brow")).getInt("rotationZ"));
        buffer.writeC(((BasicDBObject) face.get("brow")).getInt("stretchX"));
        buffer.writeC(((BasicDBObject) face.get("brow")).getInt("stretchY"));
        buffer.writeC(((BasicDBObject) face.get("brow")).getInt("stretchZ"));
        buffer.writeC(((BasicDBObject) face.get("eyebrowLeft")).getInt("positionX"));
        buffer.writeC(((BasicDBObject) face.get("eyebrowLeft")).getInt("positionY"));
        buffer.writeC(((BasicDBObject) face.get("eyebrowLeft")).getInt("positionZ"));
        buffer.writeC(((BasicDBObject) face.get("eyebrowLeft")).getInt("rotationX"));
        buffer.writeC(((BasicDBObject) face.get("eyebrowLeft")).getInt("rotationY"));
        buffer.writeC(((BasicDBObject) face.get("eyebrowLeft")).getInt("rotationZ"));
        buffer.writeC(((BasicDBObject) face.get("eyebrowLeft")).getInt("stretchX"));
        buffer.writeC(((BasicDBObject) face.get("eyebrowLeft")).getInt("stretchY"));
        buffer.writeC(((BasicDBObject) face.get("eyebrowLeft")).getInt("stretchZ"));
        buffer.writeC(((BasicDBObject) face.get("eyebrowRight")).getInt("positionX"));
        buffer.writeC(((BasicDBObject) face.get("eyebrowRight")).getInt("positionY"));
        buffer.writeC(((BasicDBObject) face.get("eyebrowRight")).getInt("positionZ"));
        buffer.writeC(((BasicDBObject) face.get("eyebrowRight")).getInt("rotationX"));
        buffer.writeC(((BasicDBObject) face.get("eyebrowRight")).getInt("rotationY"));
        buffer.writeC(((BasicDBObject) face.get("eyebrowRight")).getInt("rotationZ"));
        buffer.writeC(((BasicDBObject) face.get("eyebrowRight")).getInt("stretchX"));
        buffer.writeC(((BasicDBObject) face.get("eyebrowRight")).getInt("stretchY"));
        buffer.writeC(((BasicDBObject) face.get("eyebrowRight")).getInt("stretchZ"));
        buffer.writeC(((BasicDBObject) face.get("noseBridgeUp")).getInt("positionX"));
        buffer.writeC(((BasicDBObject) face.get("noseBridgeUp")).getInt("positionY"));
        buffer.writeC(((BasicDBObject) face.get("noseBridgeUp")).getInt("positionZ"));
        buffer.writeC(((BasicDBObject) face.get("noseBridgeUp")).getInt("rotationX"));
        buffer.writeC(((BasicDBObject) face.get("noseBridgeUp")).getInt("rotationY"));
        buffer.writeC(((BasicDBObject) face.get("noseBridgeUp")).getInt("rotationZ"));
        buffer.writeC(((BasicDBObject) face.get("noseBridgeUp")).getInt("stretchX"));
        buffer.writeC(((BasicDBObject) face.get("noseBridgeUp")).getInt("stretchY"));
        buffer.writeC(((BasicDBObject) face.get("noseBridgeUp")).getInt("stretchZ"));
        buffer.writeC(((BasicDBObject) face.get("eyebrowLeft2")).getInt("positionX"));
        buffer.writeC(((BasicDBObject) face.get("eyebrowLeft2")).getInt("positionY"));
        buffer.writeC(((BasicDBObject) face.get("eyebrowLeft2")).getInt("positionZ"));
        buffer.writeC(((BasicDBObject) face.get("eyebrowLeft2")).getInt("rotationX"));
        buffer.writeC(((BasicDBObject) face.get("eyebrowLeft2")).getInt("rotationY"));
        buffer.writeC(((BasicDBObject) face.get("eyebrowLeft2")).getInt("rotationZ"));
        buffer.writeC(((BasicDBObject) face.get("eyebrowLeft2")).getInt("stretchX"));
        buffer.writeC(((BasicDBObject) face.get("eyebrowLeft2")).getInt("stretchY"));
        buffer.writeC(((BasicDBObject) face.get("eyebrowLeft2")).getInt("stretchZ"));
        buffer.writeC(((BasicDBObject) face.get("eyebrowRight2")).getInt("positionX"));
        buffer.writeC(((BasicDBObject) face.get("eyebrowRight2")).getInt("positionY"));
        buffer.writeC(((BasicDBObject) face.get("eyebrowRight2")).getInt("positionZ"));
        buffer.writeC(((BasicDBObject) face.get("eyebrowRight2")).getInt("rotationX"));
        buffer.writeC(((BasicDBObject) face.get("eyebrowRight2")).getInt("rotationY"));
        buffer.writeC(((BasicDBObject) face.get("eyebrowRight2")).getInt("rotationZ"));
        buffer.writeC(((BasicDBObject) face.get("eyebrowRight2")).getInt("stretchX"));
        buffer.writeC(((BasicDBObject) face.get("eyebrowRight2")).getInt("stretchY"));
        buffer.writeC(((BasicDBObject) face.get("eyebrowRight2")).getInt("stretchZ"));
        buffer.writeC(((BasicDBObject) face.get("eyelidDownLeft")).getInt("positionX"));
        buffer.writeC(((BasicDBObject) face.get("eyelidDownLeft")).getInt("positionY"));
        buffer.writeC(((BasicDBObject) face.get("eyelidDownLeft")).getInt("positionZ"));
        buffer.writeC(((BasicDBObject) face.get("eyelidDownLeft")).getInt("rotationX"));
        buffer.writeC(((BasicDBObject) face.get("eyelidDownLeft")).getInt("rotationY"));
        buffer.writeC(((BasicDBObject) face.get("eyelidDownLeft")).getInt("rotationZ"));
        buffer.writeC(((BasicDBObject) face.get("eyelidDownLeft")).getInt("stretchX"));
        buffer.writeC(((BasicDBObject) face.get("eyelidDownLeft")).getInt("stretchY"));
        buffer.writeC(((BasicDBObject) face.get("eyelidDownLeft")).getInt("stretchZ"));
        buffer.writeC(((BasicDBObject) face.get("eyelidDownRight")).getInt("positionX"));
        buffer.writeC(((BasicDBObject) face.get("eyelidDownRight")).getInt("positionY"));
        buffer.writeC(((BasicDBObject) face.get("eyelidDownRight")).getInt("positionZ"));
        buffer.writeC(((BasicDBObject) face.get("eyelidDownRight")).getInt("rotationX"));
        buffer.writeC(((BasicDBObject) face.get("eyelidDownRight")).getInt("rotationY"));
        buffer.writeC(((BasicDBObject) face.get("eyelidDownRight")).getInt("rotationZ"));
        buffer.writeC(((BasicDBObject) face.get("eyelidDownRight")).getInt("stretchX"));
        buffer.writeC(((BasicDBObject) face.get("eyelidDownRight")).getInt("stretchY"));
        buffer.writeC(((BasicDBObject) face.get("eyelidDownRight")).getInt("stretchZ"));
        buffer.writeC(((BasicDBObject) face.get("eyeCornerRight")).getInt("positionX"));
        buffer.writeC(((BasicDBObject) face.get("eyeCornerRight")).getInt("positionY"));
        buffer.writeC(((BasicDBObject) face.get("eyeCornerRight")).getInt("positionZ"));
        buffer.writeC(((BasicDBObject) face.get("eyeCornerRight")).getInt("rotationX"));
        buffer.writeC(((BasicDBObject) face.get("eyeCornerRight")).getInt("rotationY"));
        buffer.writeC(((BasicDBObject) face.get("eyeCornerRight")).getInt("rotationZ"));
        buffer.writeC(((BasicDBObject) face.get("eyeCornerRight")).getInt("stretchX"));
        buffer.writeC(((BasicDBObject) face.get("eyeCornerRight")).getInt("stretchY"));
        buffer.writeC(((BasicDBObject) face.get("eyeCornerRight")).getInt("stretchZ"));
        buffer.writeC(((BasicDBObject) face.get("eyeCorner2Left")).getInt("positionX"));
        buffer.writeC(((BasicDBObject) face.get("eyeCorner2Left")).getInt("positionY"));
        buffer.writeC(((BasicDBObject) face.get("eyeCorner2Left")).getInt("positionZ"));
        buffer.writeC(((BasicDBObject) face.get("eyeCorner2Left")).getInt("rotationX"));
        buffer.writeC(((BasicDBObject) face.get("eyeCorner2Left")).getInt("rotationY"));
        buffer.writeC(((BasicDBObject) face.get("eyeCorner2Left")).getInt("rotationZ"));
        buffer.writeC(((BasicDBObject) face.get("eyeCorner2Left")).getInt("stretchX"));
        buffer.writeC(((BasicDBObject) face.get("eyeCorner2Left")).getInt("stretchY"));
        buffer.writeC(((BasicDBObject) face.get("eyeCorner2Left")).getInt("stretchZ"));
        buffer.writeC(((BasicDBObject) face.get("eyelidUpLeft")).getInt("positionX"));
        buffer.writeC(((BasicDBObject) face.get("eyelidUpLeft")).getInt("positionY"));
        buffer.writeC(((BasicDBObject) face.get("eyelidUpLeft")).getInt("positionZ"));
        buffer.writeC(((BasicDBObject) face.get("eyelidUpLeft")).getInt("rotationX"));
        buffer.writeC(((BasicDBObject) face.get("eyelidUpLeft")).getInt("rotationY"));
        buffer.writeC(((BasicDBObject) face.get("eyelidUpLeft")).getInt("rotationZ"));
        buffer.writeC(((BasicDBObject) face.get("eyelidUpLeft")).getInt("stretchX"));
        buffer.writeC(((BasicDBObject) face.get("eyelidUpLeft")).getInt("stretchY"));
        buffer.writeC(((BasicDBObject) face.get("eyelidUpLeft")).getInt("stretchZ"));
        buffer.writeC(((BasicDBObject) face.get("eyelidUpRight")).getInt("positionX"));
        buffer.writeC(((BasicDBObject) face.get("eyelidUpRight")).getInt("positionY"));
        buffer.writeC(((BasicDBObject) face.get("eyelidUpRight")).getInt("positionZ"));
        buffer.writeC(((BasicDBObject) face.get("eyelidUpRight")).getInt("rotationX"));
        buffer.writeC(((BasicDBObject) face.get("eyelidUpRight")).getInt("rotationY"));
        buffer.writeC(((BasicDBObject) face.get("eyelidUpRight")).getInt("rotationZ"));
        buffer.writeC(((BasicDBObject) face.get("eyelidUpRight")).getInt("stretchX"));
        buffer.writeC(((BasicDBObject) face.get("eyelidUpRight")).getInt("stretchY"));
        buffer.writeC(((BasicDBObject) face.get("eyelidUpRight")).getInt("stretchZ"));
        buffer.writeC(((BasicDBObject) face.get("eyeCorner2Right")).getInt("positionX"));
        buffer.writeC(((BasicDBObject) face.get("eyeCorner2Right")).getInt("positionY"));
        buffer.writeC(((BasicDBObject) face.get("eyeCorner2Right")).getInt("positionZ"));
        buffer.writeC(((BasicDBObject) face.get("eyeCorner2Right")).getInt("rotationX"));
        buffer.writeC(((BasicDBObject) face.get("eyeCorner2Right")).getInt("rotationY"));
        buffer.writeC(((BasicDBObject) face.get("eyeCorner2Right")).getInt("rotationZ"));
        buffer.writeC(((BasicDBObject) face.get("eyeCorner2Right")).getInt("stretchX"));
        buffer.writeC(((BasicDBObject) face.get("eyeCorner2Right")).getInt("stretchY"));
        buffer.writeC(((BasicDBObject) face.get("eyeCorner2Right")).getInt("stretchZ"));
        buffer.writeC(((BasicDBObject) face.get("eyeCornerLeft")).getInt("positionX"));
        buffer.writeC(((BasicDBObject) face.get("eyeCornerLeft")).getInt("positionY"));
        buffer.writeC(((BasicDBObject) face.get("eyeCornerLeft")).getInt("positionZ"));
        buffer.writeC(((BasicDBObject) face.get("eyeCornerLeft")).getInt("rotationX"));
        buffer.writeC(((BasicDBObject) face.get("eyeCornerLeft")).getInt("rotationY"));
        buffer.writeC(((BasicDBObject) face.get("eyeCornerLeft")).getInt("rotationZ"));
        buffer.writeC(((BasicDBObject) face.get("eyeCornerLeft")).getInt("stretchX"));
        buffer.writeC(((BasicDBObject) face.get("eyeCornerLeft")).getInt("stretchY"));
        buffer.writeC(((BasicDBObject) face.get("eyeCornerLeft")).getInt("stretchZ"));
        buffer.writeC(((BasicDBObject) face.get("eyeLeft")).getInt("positionX"));
        buffer.writeC(((BasicDBObject) face.get("eyeLeft")).getInt("positionY"));
        buffer.writeC(((BasicDBObject) face.get("eyeLeft")).getInt("positionZ"));
        buffer.writeC(((BasicDBObject) face.get("eyeLeft")).getInt("rotationX"));
        buffer.writeC(((BasicDBObject) face.get("eyeLeft")).getInt("rotationY"));
        buffer.writeC(((BasicDBObject) face.get("eyeLeft")).getInt("rotationZ"));
        buffer.writeC(((BasicDBObject) face.get("eyeLeft")).getInt("stretchX"));
        buffer.writeC(((BasicDBObject) face.get("eyeLeft")).getInt("stretchY"));
        buffer.writeC(((BasicDBObject) face.get("eyeLeft")).getInt("stretchZ"));
        buffer.writeC(((BasicDBObject) face.get("eyeRight")).getInt("positionX"));
        buffer.writeC(((BasicDBObject) face.get("eyeRight")).getInt("positionY"));
        buffer.writeC(((BasicDBObject) face.get("eyeRight")).getInt("positionZ"));
        buffer.writeC(((BasicDBObject) face.get("eyeRight")).getInt("rotationX"));
        buffer.writeC(((BasicDBObject) face.get("eyeRight")).getInt("rotationY"));
        buffer.writeC(((BasicDBObject) face.get("eyeRight")).getInt("rotationZ"));
        buffer.writeC(((BasicDBObject) face.get("eyeRight")).getInt("stretchX"));
        buffer.writeC(((BasicDBObject) face.get("eyeRight")).getInt("stretchY"));
        buffer.writeC(((BasicDBObject) face.get("eyeRight")).getInt("stretchZ"));
        buffer.writeC(((BasicDBObject) face.get("cheekCrownLeft")).getInt("positionX"));
        buffer.writeC(((BasicDBObject) face.get("cheekCrownLeft")).getInt("positionY"));
        buffer.writeC(((BasicDBObject) face.get("cheekCrownLeft")).getInt("positionZ"));
        buffer.writeC(((BasicDBObject) face.get("cheekCrownLeft")).getInt("rotationX"));
        buffer.writeC(((BasicDBObject) face.get("cheekCrownLeft")).getInt("rotationY"));
        buffer.writeC(((BasicDBObject) face.get("cheekCrownLeft")).getInt("rotationZ"));
        buffer.writeC(((BasicDBObject) face.get("cheekCrownLeft")).getInt("stretchX"));
        buffer.writeC(((BasicDBObject) face.get("cheekCrownLeft")).getInt("stretchY"));
        buffer.writeC(((BasicDBObject) face.get("cheekCrownLeft")).getInt("stretchZ"));
        buffer.writeC(((BasicDBObject) face.get("cheekCrownRight")).getInt("positionX"));
        buffer.writeC(((BasicDBObject) face.get("cheekCrownRight")).getInt("positionY"));
        buffer.writeC(((BasicDBObject) face.get("cheekCrownRight")).getInt("positionZ"));
        buffer.writeC(((BasicDBObject) face.get("cheekCrownRight")).getInt("rotationX"));
        buffer.writeC(((BasicDBObject) face.get("cheekCrownRight")).getInt("rotationY"));
        buffer.writeC(((BasicDBObject) face.get("cheekCrownRight")).getInt("rotationZ"));
        buffer.writeC(((BasicDBObject) face.get("cheekCrownRight")).getInt("stretchX"));
        buffer.writeC(((BasicDBObject) face.get("cheekCrownRight")).getInt("stretchY"));
        buffer.writeC(((BasicDBObject) face.get("cheekCrownRight")).getInt("stretchZ"));
        buffer.writeC(((BasicDBObject) face.get("noseCheekLeft")).getInt("positionX"));
        buffer.writeC(((BasicDBObject) face.get("noseCheekLeft")).getInt("positionY"));
        buffer.writeC(((BasicDBObject) face.get("noseCheekLeft")).getInt("positionZ"));
        buffer.writeC(((BasicDBObject) face.get("noseCheekLeft")).getInt("rotationX"));
        buffer.writeC(((BasicDBObject) face.get("noseCheekLeft")).getInt("rotationY"));
        buffer.writeC(((BasicDBObject) face.get("noseCheekLeft")).getInt("rotationZ"));
        buffer.writeC(((BasicDBObject) face.get("noseCheekLeft")).getInt("stretchX"));
        buffer.writeC(((BasicDBObject) face.get("noseCheekLeft")).getInt("stretchY"));
        buffer.writeC(((BasicDBObject) face.get("noseCheekLeft")).getInt("stretchZ"));
        buffer.writeC(((BasicDBObject) face.get("noseCheekRight")).getInt("positionX"));
        buffer.writeC(((BasicDBObject) face.get("noseCheekRight")).getInt("positionY"));
        buffer.writeC(((BasicDBObject) face.get("noseCheekRight")).getInt("positionZ"));
        buffer.writeC(((BasicDBObject) face.get("noseCheekRight")).getInt("rotationX"));
        buffer.writeC(((BasicDBObject) face.get("noseCheekRight")).getInt("rotationY"));
        buffer.writeC(((BasicDBObject) face.get("noseCheekRight")).getInt("rotationZ"));
        buffer.writeC(((BasicDBObject) face.get("noseCheekRight")).getInt("stretchX"));
        buffer.writeC(((BasicDBObject) face.get("noseCheekRight")).getInt("stretchY"));
        buffer.writeC(((BasicDBObject) face.get("noseCheekRight")).getInt("stretchZ"));
        buffer.writeC(((BasicDBObject) face.get("nose")).getInt("positionX"));
        buffer.writeC(((BasicDBObject) face.get("nose")).getInt("positionY"));
        buffer.writeC(((BasicDBObject) face.get("nose")).getInt("positionZ"));
        buffer.writeC(((BasicDBObject) face.get("nose")).getInt("rotationX"));
        buffer.writeC(((BasicDBObject) face.get("nose")).getInt("rotationY"));
        buffer.writeC(((BasicDBObject) face.get("nose")).getInt("rotationZ"));
        buffer.writeC(((BasicDBObject) face.get("nose")).getInt("stretchX"));
        buffer.writeC(((BasicDBObject) face.get("nose")).getInt("stretchY"));
        buffer.writeC(((BasicDBObject) face.get("nose")).getInt("stretchZ"));
        buffer.writeC(((BasicDBObject) face.get("noseCheek2Left")).getInt("positionX"));
        buffer.writeC(((BasicDBObject) face.get("noseCheek2Left")).getInt("positionY"));
        buffer.writeC(((BasicDBObject) face.get("noseCheek2Left")).getInt("positionZ"));
        buffer.writeC(((BasicDBObject) face.get("noseCheek2Left")).getInt("rotationX"));
        buffer.writeC(((BasicDBObject) face.get("noseCheek2Left")).getInt("rotationY"));
        buffer.writeC(((BasicDBObject) face.get("noseCheek2Left")).getInt("rotationZ"));
        buffer.writeC(((BasicDBObject) face.get("noseCheek2Left")).getInt("stretchX"));
        buffer.writeC(((BasicDBObject) face.get("noseCheek2Left")).getInt("stretchY"));
        buffer.writeC(((BasicDBObject) face.get("noseCheek2Left")).getInt("stretchZ"));
        buffer.writeC(((BasicDBObject) face.get("noseCheek2Right")).getInt("positionX"));
        buffer.writeC(((BasicDBObject) face.get("noseCheek2Right")).getInt("positionY"));
        buffer.writeC(((BasicDBObject) face.get("noseCheek2Right")).getInt("positionZ"));
        buffer.writeC(((BasicDBObject) face.get("noseCheek2Right")).getInt("rotationX"));
        buffer.writeC(((BasicDBObject) face.get("noseCheek2Right")).getInt("rotationY"));
        buffer.writeC(((BasicDBObject) face.get("noseCheek2Right")).getInt("rotationZ"));
        buffer.writeC(((BasicDBObject) face.get("noseCheek2Right")).getInt("stretchX"));
        buffer.writeC(((BasicDBObject) face.get("noseCheek2Right")).getInt("stretchY"));
        buffer.writeC(((BasicDBObject) face.get("noseCheek2Right")).getInt("stretchZ"));
        buffer.writeC(((BasicDBObject) face.get("noseBridge")).getInt("positionX"));
        buffer.writeC(((BasicDBObject) face.get("noseBridge")).getInt("positionY"));
        buffer.writeC(((BasicDBObject) face.get("noseBridge")).getInt("positionZ"));
        buffer.writeC(((BasicDBObject) face.get("noseBridge")).getInt("rotationX"));
        buffer.writeC(((BasicDBObject) face.get("noseBridge")).getInt("rotationY"));
        buffer.writeC(((BasicDBObject) face.get("noseBridge")).getInt("rotationZ"));
        buffer.writeC(((BasicDBObject) face.get("noseBridge")).getInt("stretchX"));
        buffer.writeC(((BasicDBObject) face.get("noseBridge")).getInt("stretchY"));
        buffer.writeC(((BasicDBObject) face.get("noseBridge")).getInt("stretchZ"));
        buffer.writeC(((BasicDBObject) face.get("lipCenterUp")).getInt("positionX"));
        buffer.writeC(((BasicDBObject) face.get("lipCenterUp")).getInt("positionY"));
        buffer.writeC(((BasicDBObject) face.get("lipCenterUp")).getInt("positionZ"));
        buffer.writeC(((BasicDBObject) face.get("lipCenterUp")).getInt("rotationX"));
        buffer.writeC(((BasicDBObject) face.get("lipCenterUp")).getInt("rotationY"));
        buffer.writeC(((BasicDBObject) face.get("lipCenterUp")).getInt("rotationZ"));
        buffer.writeC(((BasicDBObject) face.get("lipCenterUp")).getInt("stretchX"));
        buffer.writeC(((BasicDBObject) face.get("lipCenterUp")).getInt("stretchY"));
        buffer.writeC(((BasicDBObject) face.get("lipCenterUp")).getInt("stretchZ"));
        buffer.writeC(((BasicDBObject) face.get("lipSideUpLeft")).getInt("positionX"));
        buffer.writeC(((BasicDBObject) face.get("lipSideUpLeft")).getInt("positionY"));
        buffer.writeC(((BasicDBObject) face.get("lipSideUpLeft")).getInt("positionZ"));
        buffer.writeC(((BasicDBObject) face.get("lipSideUpLeft")).getInt("rotationX"));
        buffer.writeC(((BasicDBObject) face.get("lipSideUpLeft")).getInt("rotationY"));
        buffer.writeC(((BasicDBObject) face.get("lipSideUpLeft")).getInt("rotationZ"));
        buffer.writeC(((BasicDBObject) face.get("lipSideUpLeft")).getInt("stretchX"));
        buffer.writeC(((BasicDBObject) face.get("lipSideUpLeft")).getInt("stretchY"));
        buffer.writeC(((BasicDBObject) face.get("lipSideUpLeft")).getInt("stretchZ"));
        buffer.writeC(((BasicDBObject) face.get("lipSideUpRight")).getInt("positionX"));
        buffer.writeC(((BasicDBObject) face.get("lipSideUpRight")).getInt("positionY"));
        buffer.writeC(((BasicDBObject) face.get("lipSideUpRight")).getInt("positionZ"));
        buffer.writeC(((BasicDBObject) face.get("lipSideUpRight")).getInt("rotationX"));
        buffer.writeC(((BasicDBObject) face.get("lipSideUpRight")).getInt("rotationY"));
        buffer.writeC(((BasicDBObject) face.get("lipSideUpRight")).getInt("rotationZ"));
        buffer.writeC(((BasicDBObject) face.get("lipSideUpRight")).getInt("stretchX"));
        buffer.writeC(((BasicDBObject) face.get("lipSideUpRight")).getInt("stretchY"));
        buffer.writeC(((BasicDBObject) face.get("lipSideUpRight")).getInt("stretchZ"));
        buffer.writeC(((BasicDBObject) face.get("lipSide2UpLeft")).getInt("positionX"));
        buffer.writeC(((BasicDBObject) face.get("lipSide2UpLeft")).getInt("positionY"));
        buffer.writeC(((BasicDBObject) face.get("lipSide2UpLeft")).getInt("positionZ"));
        buffer.writeC(((BasicDBObject) face.get("lipSide2UpLeft")).getInt("rotationX"));
        buffer.writeC(((BasicDBObject) face.get("lipSide2UpLeft")).getInt("rotationY"));
        buffer.writeC(((BasicDBObject) face.get("lipSide2UpLeft")).getInt("rotationZ"));
        buffer.writeC(((BasicDBObject) face.get("lipSide2UpLeft")).getInt("stretchX"));
        buffer.writeC(((BasicDBObject) face.get("lipSide2UpLeft")).getInt("stretchY"));
        buffer.writeC(((BasicDBObject) face.get("lipSide2UpLeft")).getInt("stretchZ"));
        buffer.writeC(((BasicDBObject) face.get("lipSide2UpRight")).getInt("positionX"));
        buffer.writeC(((BasicDBObject) face.get("lipSide2UpRight")).getInt("positionY"));
        buffer.writeC(((BasicDBObject) face.get("lipSide2UpRight")).getInt("positionZ"));
        buffer.writeC(((BasicDBObject) face.get("lipSide2UpRight")).getInt("rotationX"));
        buffer.writeC(((BasicDBObject) face.get("lipSide2UpRight")).getInt("rotationY"));
        buffer.writeC(((BasicDBObject) face.get("lipSide2UpRight")).getInt("rotationZ"));
        buffer.writeC(((BasicDBObject) face.get("lipSide2UpRight")).getInt("stretchX"));
        buffer.writeC(((BasicDBObject) face.get("lipSide2UpRight")).getInt("stretchY"));
        buffer.writeC(((BasicDBObject) face.get("lipSide2UpRight")).getInt("stretchZ"));
        buffer.writeC(((BasicDBObject) face.get("lipSideDownLeft")).getInt("positionX"));
        buffer.writeC(((BasicDBObject) face.get("lipSideDownLeft")).getInt("positionY"));
        buffer.writeC(((BasicDBObject) face.get("lipSideDownLeft")).getInt("positionZ"));
        buffer.writeC(((BasicDBObject) face.get("lipSideDownLeft")).getInt("rotationX"));
        buffer.writeC(((BasicDBObject) face.get("lipSideDownLeft")).getInt("rotationY"));
        buffer.writeC(((BasicDBObject) face.get("lipSideDownLeft")).getInt("rotationZ"));
        buffer.writeC(((BasicDBObject) face.get("lipSideDownLeft")).getInt("stretchX"));
        buffer.writeC(((BasicDBObject) face.get("lipSideDownLeft")).getInt("stretchY"));
        buffer.writeC(((BasicDBObject) face.get("lipSideDownLeft")).getInt("stretchZ"));
        buffer.writeC(((BasicDBObject) face.get("lipSideDownRight")).getInt("positionX"));
        buffer.writeC(((BasicDBObject) face.get("lipSideDownRight")).getInt("positionY"));
        buffer.writeC(((BasicDBObject) face.get("lipSideDownRight")).getInt("positionZ"));
        buffer.writeC(((BasicDBObject) face.get("lipSideDownRight")).getInt("rotationX"));
        buffer.writeC(((BasicDBObject) face.get("lipSideDownRight")).getInt("rotationY"));
        buffer.writeC(((BasicDBObject) face.get("lipSideDownRight")).getInt("rotationZ"));
        buffer.writeC(((BasicDBObject) face.get("lipSideDownRight")).getInt("stretchX"));
        buffer.writeC(((BasicDBObject) face.get("lipSideDownRight")).getInt("stretchY"));
        buffer.writeC(((BasicDBObject) face.get("lipSideDownRight")).getInt("stretchZ"));
        buffer.writeC(((BasicDBObject) face.get("lipCenterDown")).getInt("positionX"));
        buffer.writeC(((BasicDBObject) face.get("lipCenterDown")).getInt("positionY"));
        buffer.writeC(((BasicDBObject) face.get("lipCenterDown")).getInt("positionZ"));
        buffer.writeC(((BasicDBObject) face.get("lipCenterDown")).getInt("rotationX"));
        buffer.writeC(((BasicDBObject) face.get("lipCenterDown")).getInt("rotationY"));
        buffer.writeC(((BasicDBObject) face.get("lipCenterDown")).getInt("rotationZ"));
        buffer.writeC(((BasicDBObject) face.get("lipCenterDown")).getInt("stretchX"));
        buffer.writeC(((BasicDBObject) face.get("lipCenterDown")).getInt("stretchY"));
        buffer.writeC(((BasicDBObject) face.get("lipCenterDown")).getInt("stretchZ"));
        buffer.writeC(0);
        buffer.writeC(body.getInt("height"));
        buffer.writeC(0);
        buffer.writeC(((BasicDBObject) body.get("calvesLeft")).getInt("stretchX"));
        buffer.writeC(((BasicDBObject) body.get("calvesLeft")).getInt("stretchY"));
        buffer.writeC(((BasicDBObject) body.get("calvesLeft")).getInt("stretchZ"));
        buffer.writeC(((BasicDBObject) body.get("calvesRight")).getInt("stretchX"));
        buffer.writeC(((BasicDBObject) body.get("calvesRight")).getInt("stretchY"));
        buffer.writeC(((BasicDBObject) body.get("calvesRight")).getInt("stretchZ"));
        buffer.writeC(((BasicDBObject) body.get("thighLeft")).getInt("stretchX"));
        buffer.writeC(((BasicDBObject) body.get("thighLeft")).getInt("stretchY"));
        buffer.writeC(((BasicDBObject) body.get("thighLeft")).getInt("stretchZ"));
        buffer.writeC(((BasicDBObject) body.get("thighRight")).getInt("stretchX"));
        buffer.writeC(((BasicDBObject) body.get("thighRight")).getInt("stretchY"));
        buffer.writeC(((BasicDBObject) body.get("thighRight")).getInt("stretchZ"));
        buffer.writeC(((BasicDBObject) body.get("footLeft")).getInt("stretchX"));
        buffer.writeC(((BasicDBObject) body.get("footLeft")).getInt("stretchY"));
        buffer.writeC(((BasicDBObject) body.get("footLeft")).getInt("stretchZ"));
        buffer.writeC(((BasicDBObject) body.get("footRight")).getInt("stretchX"));
        buffer.writeC(((BasicDBObject) body.get("footRight")).getInt("stretchY"));
        buffer.writeC(((BasicDBObject) body.get("footRight")).getInt("stretchZ"));
        buffer.writeC(((BasicDBObject) body.get("neck")).getInt("stretchX"));
        buffer.writeC(((BasicDBObject) body.get("neck")).getInt("stretchY"));
        buffer.writeC(((BasicDBObject) body.get("neck")).getInt("stretchZ"));
        buffer.writeC(((BasicDBObject) body.get("groin")).getInt("stretchX"));
        buffer.writeC(((BasicDBObject) body.get("groin")).getInt("stretchY"));
        buffer.writeC(((BasicDBObject) body.get("groin")).getInt("stretchZ"));
        buffer.writeC(((BasicDBObject) body.get("stomach")).getInt("stretchX"));
        buffer.writeC(((BasicDBObject) body.get("stomach")).getInt("stretchY"));
        buffer.writeC(((BasicDBObject) body.get("stomach")).getInt("stretchZ"));
        buffer.writeC(((BasicDBObject) body.get("chest")).getInt("stretchX"));
        buffer.writeC(((BasicDBObject) body.get("chest")).getInt("stretchY"));
        buffer.writeC(((BasicDBObject) body.get("chest")).getInt("stretchZ"));
        buffer.writeC(((BasicDBObject) body.get("breast")).getInt("stretchX"));
        buffer.writeC(((BasicDBObject) body.get("breast")).getInt("stretchY"));
        buffer.writeC(((BasicDBObject) body.get("breast")).getInt("stretchZ"));
        buffer.writeC(((BasicDBObject) body.get("buttockLeft")).getInt("stretchX"));
        buffer.writeC(((BasicDBObject) body.get("buttockLeft")).getInt("stretchY"));
        buffer.writeC(((BasicDBObject) body.get("buttockLeft")).getInt("stretchZ"));
        buffer.writeC(((BasicDBObject) body.get("buttockRight")).getInt("stretchX"));
        buffer.writeC(((BasicDBObject) body.get("buttockRight")).getInt("stretchY"));
        buffer.writeC(((BasicDBObject) body.get("buttockRight")).getInt("stretchZ"));
        buffer.writeC(((BasicDBObject) body.get("shouldersLeft")).getInt("stretchX"));
        buffer.writeC(((BasicDBObject) body.get("shouldersLeft")).getInt("stretchY"));
        buffer.writeC(((BasicDBObject) body.get("shouldersLeft")).getInt("stretchZ"));
        buffer.writeC(((BasicDBObject) body.get("shouldersRight")).getInt("stretchX"));
        buffer.writeC(((BasicDBObject) body.get("shouldersRight")).getInt("stretchY"));
        buffer.writeC(((BasicDBObject) body.get("shouldersRight")).getInt("stretchZ"));
        buffer.writeC(((BasicDBObject) body.get("forearmLeft")).getInt("stretchX"));
        buffer.writeC(((BasicDBObject) body.get("forearmLeft")).getInt("stretchY"));
        buffer.writeC(((BasicDBObject) body.get("forearmLeft")).getInt("stretchZ"));
        buffer.writeC(((BasicDBObject) body.get("forearmRight")).getInt("stretchX"));
        buffer.writeC(((BasicDBObject) body.get("forearmRight")).getInt("stretchY"));
        buffer.writeC(((BasicDBObject) body.get("forearmRight")).getInt("stretchZ"));
        buffer.writeC(((BasicDBObject) body.get("armLeft")).getInt("stretchX"));
        buffer.writeC(((BasicDBObject) body.get("armLeft")).getInt("stretchY"));
        buffer.writeC(((BasicDBObject) body.get("armLeft")).getInt("stretchZ"));
        buffer.writeC(((BasicDBObject) body.get("armRight")).getInt("stretchX"));
        buffer.writeC(((BasicDBObject) body.get("armRight")).getInt("stretchY"));
        buffer.writeC(((BasicDBObject) body.get("armRight")).getInt("stretchZ"));
        buffer.writeC(((BasicDBObject) body.get("handLeft")).getInt("stretchX"));
        buffer.writeC(((BasicDBObject) body.get("handLeft")).getInt("stretchY"));
        buffer.writeC(((BasicDBObject) body.get("handLeft")).getInt("stretchZ"));
        buffer.writeC(((BasicDBObject) body.get("handRight")).getInt("stretchX"));
        buffer.writeC(((BasicDBObject) body.get("handRight")).getInt("stretchY"));
        buffer.writeC(((BasicDBObject) body.get("handRight")).getInt("stretchZ"));
        buffer.writeB((byte[]) body.get("additionalSizeData"));
        buffer.writeB((byte[]) hairs.get("additionalSizeData"));
        buffer.writeC(tattoo.getInt("faceTattooId"));
        buffer.writeC(tattoo.getInt("bodyTattooId"));
        buffer.writeC(hairs.getInt("length"));
        buffer.writeC(hairs.getInt("backLength"));
        buffer.writeC(hairs.getInt("sideLength"));
        buffer.writeC(hairs.getInt("curls"));
        buffer.writeC(hairs.getInt("swirls"));
        buffer.writeC(hairs.getInt("shine"));
        buffer.writeC(hairs.getInt("colorId"));
        buffer.writeC(hairs.getInt("tipsSaturation"));
        buffer.writeC(hairs.getInt("tipsLength"));
        buffer.writeC(hairs.getInt("tipsColorId"));
        buffer.writeC(hairs.getInt("rootsSaturation"));
        buffer.writeC(hairs.getInt("rootsLength"));
        buffer.writeC(hairs.getInt("rootsColorId"));
        buffer.writeC(face.getInt("colorId"));
        buffer.writeC(face.getInt("shine"));
        if (EClassType.valueOf(player.getInt("classType")).getGenderType() == EGenderType.Woman) {
            buffer.writeC(((BasicDBObject) face.get("eyeMakeUp")).getInt("_id"));
            buffer.writeC(((BasicDBObject) face.get("eyeMakeUp")).getInt("density"));
            buffer.writeC(((BasicDBObject) face.get("eyeMakeUp")).getInt("highlight"));
            buffer.writeC(((BasicDBObject) face.get("eyeMakeUp")).getInt("shine"));
            buffer.writeC(((BasicDBObject) face.get("eyeMakeUp")).getInt("area"));
            buffer.writeC(((BasicDBObject) face.get("eyeMakeUp")).getInt("colorId"));
            buffer.writeC(((BasicDBObject) face.get("eyebrowsMakeUp")).getInt("_id"));
            buffer.writeC(((BasicDBObject) face.get("eyebrowsMakeUp")).getInt("density"));
            buffer.writeC(((BasicDBObject) face.get("eyebrowsMakeUp")).getInt("highlight"));
            buffer.writeC(((BasicDBObject) face.get("eyebrowsMakeUp")).getInt("shine"));
            buffer.writeC(((BasicDBObject) face.get("eyebrowsMakeUp")).getInt("area"));
            buffer.writeC(((BasicDBObject) face.get("eyebrowsMakeUp")).getInt("colorId"));
            buffer.writeC(((BasicDBObject) face.get("rougeMakeUp")).getInt("_id"));
            buffer.writeC(((BasicDBObject) face.get("rougeMakeUp")).getInt("density"));
            buffer.writeC(((BasicDBObject) face.get("rougeMakeUp")).getInt("highlight"));
            buffer.writeC(((BasicDBObject) face.get("rougeMakeUp")).getInt("shine"));
            buffer.writeC(((BasicDBObject) face.get("rougeMakeUp")).getInt("area"));
            buffer.writeC(((BasicDBObject) face.get("rougeMakeUp")).getInt("colorId"));
            buffer.writeC(((BasicDBObject) face.get("lipsMakeUp")).getInt("_id"));
            buffer.writeC(((BasicDBObject) face.get("lipsMakeUp")).getInt("density"));
            buffer.writeC(((BasicDBObject) face.get("lipsMakeUp")).getInt("highlight"));
            buffer.writeC(((BasicDBObject) face.get("lipsMakeUp")).getInt("shine"));
            buffer.writeC(((BasicDBObject) face.get("lipsMakeUp")).getInt("area"));
            buffer.writeC(((BasicDBObject) face.get("lipsMakeUp")).getInt("colorId"));
            buffer.writeC(tattoo.getInt("faceTattooX"));
            buffer.writeC(tattoo.getInt("faceTattooY"));
            buffer.writeC(tattoo.getInt("faceTattooRotation"));
            buffer.writeC(tattoo.getInt("faceTattooWidth"));
            buffer.writeC(tattoo.getInt("faceTattooHeight"));
            buffer.writeC(tattoo.getInt("faceTattooDensity"));
            buffer.writeC(tattoo.getInt("faceTattooShine"));
            buffer.writeC(tattoo.getInt("faceTattooColorId"));
            buffer.writeC(face.getInt("wrinklesBrow"));
            buffer.writeC(face.getInt("wrinklesEyes"));
            buffer.writeC(face.getInt("wrinklesLips"));
            buffer.writeC(((BasicDBObject) face.get("eyelashesMakeUp")).getInt("_id"));
            buffer.writeC(((BasicDBObject) face.get("eyelashesMakeUp")).getInt("length"));
            buffer.writeC(((BasicDBObject) face.get("eyelashesMakeUp")).getInt("colorId"));
            buffer.writeC(((BasicDBObject) face.get("eyeShadowsMakeUp")).getInt("_id"));
            buffer.writeC(((BasicDBObject) face.get("eyeShadowsMakeUp")).getInt("length"));
            buffer.writeC(((BasicDBObject) face.get("eyeShadowsMakeUp")).getInt("colorId"));
            buffer.writeC(((BasicDBObject) face.get("eyelinerMakeUp")).getInt("_id"));
            buffer.writeC(((BasicDBObject) face.get("eyelinerMakeUp")).getInt("length"));
            buffer.writeC(((BasicDBObject) face.get("eyelinerMakeUp")).getInt("colorId"));
            buffer.writeC(((BasicDBObject) face.get("leftEyePupil")).getInt("_id"));
            buffer.writeC(((BasicDBObject) face.get("leftEyePupil")).getInt("purity"));
            buffer.writeC(((BasicDBObject) face.get("leftEyePupil")).getInt("size"));
            buffer.writeC(((BasicDBObject) face.get("leftEyePupil")).getInt("width"));
            buffer.writeC(((BasicDBObject) face.get("leftEyePupil")).getInt("area"));
            buffer.writeC(((BasicDBObject) face.get("leftEyePupil")).getInt("colorId"));
            buffer.writeC(((BasicDBObject) face.get("leftEyeIris")).getInt("_id"));
            buffer.writeC(((BasicDBObject) face.get("leftEyeIris")).getInt("purity"));
            buffer.writeC(((BasicDBObject) face.get("leftEyeIris")).getInt("size"));
            buffer.writeC(((BasicDBObject) face.get("leftEyeIris")).getInt("width"));
            buffer.writeC(((BasicDBObject) face.get("leftEyeIris")).getInt("area"));
            buffer.writeC(((BasicDBObject) face.get("leftEyeIris")).getInt("colorId"));
            buffer.writeC(((BasicDBObject) face.get("leftEyeLenses")).getInt("_id"));
            buffer.writeC(((BasicDBObject) face.get("leftEyeLenses")).getInt("purity"));
            buffer.writeC(((BasicDBObject) face.get("leftEyeLenses")).getInt("height"));
            buffer.writeC(((BasicDBObject) face.get("leftEyeLenses")).getInt("highlight"));
            buffer.writeC(((BasicDBObject) face.get("leftEyeLenses")).getInt("shine"));
            buffer.writeC(((BasicDBObject) face.get("leftEyeLenses")).getInt("colorId"));
            buffer.writeC(((BasicDBObject) face.get("rightEyePupil")).getInt("_id"));
            buffer.writeC(((BasicDBObject) face.get("rightEyePupil")).getInt("purity"));
            buffer.writeC(((BasicDBObject) face.get("rightEyePupil")).getInt("size"));
            buffer.writeC(((BasicDBObject) face.get("rightEyePupil")).getInt("width"));
            buffer.writeC(((BasicDBObject) face.get("rightEyePupil")).getInt("area"));
            buffer.writeC(((BasicDBObject) face.get("rightEyePupil")).getInt("colorId"));
            buffer.writeC(((BasicDBObject) face.get("rightEyeIris")).getInt("_id"));
            buffer.writeC(((BasicDBObject) face.get("rightEyeIris")).getInt("purity"));
            buffer.writeC(((BasicDBObject) face.get("rightEyeIris")).getInt("size"));
            buffer.writeC(((BasicDBObject) face.get("rightEyeIris")).getInt("width"));
            buffer.writeC(((BasicDBObject) face.get("rightEyeIris")).getInt("area"));
            buffer.writeC(((BasicDBObject) face.get("rightEyeIris")).getInt("colorId"));
            buffer.writeC(((BasicDBObject) face.get("rightEyeLenses")).getInt("_id"));
            buffer.writeC(((BasicDBObject) face.get("rightEyeLenses")).getInt("purity"));
            buffer.writeC(((BasicDBObject) face.get("rightEyeLenses")).getInt("height"));
            buffer.writeC(((BasicDBObject) face.get("rightEyeLenses")).getInt("highlight"));
            buffer.writeC(((BasicDBObject) face.get("rightEyeLenses")).getInt("shine"));
            buffer.writeC(((BasicDBObject) face.get("rightEyeLenses")).getInt("colorId"));
            buffer.writeC(body.getInt("chestMuscles"));
            buffer.writeC(body.getInt("armsMuscles"));
            buffer.writeC(body.getInt("legsMuscles"));
            buffer.writeC(tattoo.getInt("bodyTattooX"));
            buffer.writeC(tattoo.getInt("bodyTattooY"));
            buffer.writeC(tattoo.getInt("bodyTattooRotation"));
            buffer.writeC(tattoo.getInt("bodyTattooWidth"));
            buffer.writeC(tattoo.getInt("bodyTattooHeight"));
            buffer.writeC(tattoo.getInt("bodyTattooDensity"));
            buffer.writeC(tattoo.getInt("bodyTattooShine"));
            buffer.writeC(tattoo.getInt("bodyTattooColorId"));
            buffer.writeB(new byte[22]);
        } else {
            buffer.writeC(((BasicDBObject) face.get("bristle")).getInt("_id"));
            buffer.writeC(((BasicDBObject) face.get("bristle")).getInt("density"));
            buffer.writeC(((BasicDBObject) face.get("bristle")).getInt("shine"));
            buffer.writeC(((BasicDBObject) face.get("bristle")).getInt("area"));
            buffer.writeC(((BasicDBObject) face.get("bristle")).getInt("colorId"));
            buffer.writeC(((BasicDBObject) face.get("beard")).getInt("length"));
            buffer.writeC(((BasicDBObject) face.get("beard")).getInt("curls"));
            buffer.writeC(((BasicDBObject) face.get("beard")).getInt("swirls"));
            buffer.writeC(((BasicDBObject) face.get("beard")).getInt("colorId"));
            buffer.writeC(((BasicDBObject) face.get("mustache")).getInt("length"));
            buffer.writeC(((BasicDBObject) face.get("mustache")).getInt("curls"));
            buffer.writeC(((BasicDBObject) face.get("mustache")).getInt("swirls"));
            buffer.writeC(((BasicDBObject) face.get("mustache")).getInt("colorId"));
            buffer.writeC(((BasicDBObject) face.get("whiskers")).getInt("length"));
            buffer.writeC(((BasicDBObject) face.get("whiskers")).getInt("curls"));
            buffer.writeC(((BasicDBObject) face.get("whiskers")).getInt("swirls"));
            buffer.writeC(((BasicDBObject) face.get("whiskers")).getInt("colorId"));
            buffer.writeC(((BasicDBObject) face.get("eyebrowsMakeUp")).getInt("_id"));
            buffer.writeC(((BasicDBObject) face.get("eyebrowsMakeUp")).getInt("density"));
            buffer.writeC(((BasicDBObject) face.get("eyebrowsMakeUp")).getInt("height"));
            buffer.writeC(((BasicDBObject) face.get("eyebrowsMakeUp")).getInt("shine"));
            buffer.writeC(((BasicDBObject) face.get("eyebrowsMakeUp")).getInt("area"));
            buffer.writeC(((BasicDBObject) face.get("eyebrowsMakeUp")).getInt("colorId"));
            buffer.writeC(((BasicDBObject) face.get("eyebrows")).getInt("length"));
            buffer.writeC(((BasicDBObject) face.get("eyebrows")).getInt("curls"));
            buffer.writeC(((BasicDBObject) face.get("eyebrows")).getInt("swirls"));
            buffer.writeC(((BasicDBObject) face.get("eyebrows")).getInt("colorId"));
            buffer.writeC(((BasicDBObject) face.get("eyeMakeUp")).getInt("_id"));
            buffer.writeC(((BasicDBObject) face.get("eyeMakeUp")).getInt("density"));
            buffer.writeC(((BasicDBObject) face.get("eyeMakeUp")).getInt("highlight"));
            buffer.writeC(((BasicDBObject) face.get("eyeMakeUp")).getInt("shine"));
            buffer.writeC(((BasicDBObject) face.get("eyeMakeUp")).getInt("area"));
            buffer.writeC(((BasicDBObject) face.get("eyeMakeUp")).getInt("colorId"));
            buffer.writeC(((BasicDBObject) face.get("lipsMakeUp")).getInt("_id"));
            buffer.writeC(((BasicDBObject) face.get("lipsMakeUp")).getInt("density"));
            buffer.writeC(((BasicDBObject) face.get("lipsMakeUp")).getInt("highlight"));
            buffer.writeC(((BasicDBObject) face.get("lipsMakeUp")).getInt("shine"));
            buffer.writeC(((BasicDBObject) face.get("lipsMakeUp")).getInt("area"));
            buffer.writeC(((BasicDBObject) face.get("lipsMakeUp")).getInt("colorId"));
            buffer.writeC(tattoo.getInt("faceTattooX"));
            buffer.writeC(tattoo.getInt("faceTattooY"));
            buffer.writeC(tattoo.getInt("faceTattooRotation"));
            buffer.writeC(tattoo.getInt("faceTattooWidth"));
            buffer.writeC(tattoo.getInt("faceTattooHeight"));
            buffer.writeC(tattoo.getInt("faceTattooDensity"));
            buffer.writeC(tattoo.getInt("faceTattooShine"));
            buffer.writeC(tattoo.getInt("faceTattooColorId"));
            buffer.writeC(face.getInt("wrinklesBrow"));
            buffer.writeC(face.getInt("wrinklesEyes"));
            buffer.writeC(face.getInt("wrinklesLips"));
            buffer.writeC(((BasicDBObject) face.get("eyelashesMakeUp")).getInt("_id"));
            buffer.writeC(((BasicDBObject) face.get("eyelashesMakeUp")).getInt("length"));
            buffer.writeC(((BasicDBObject) face.get("eyelashesMakeUp")).getInt("colorId"));
            buffer.writeC(((BasicDBObject) face.get("eyeShadowsMakeUp")).getInt("_id"));
            buffer.writeC(((BasicDBObject) face.get("eyeShadowsMakeUp")).getInt("length"));
            buffer.writeC(((BasicDBObject) face.get("eyeShadowsMakeUp")).getInt("colorId"));
            buffer.writeC(((BasicDBObject) face.get("eyelinerMakeUp")).getInt("_id"));
            buffer.writeC(((BasicDBObject) face.get("eyelinerMakeUp")).getInt("length"));
            buffer.writeC(((BasicDBObject) face.get("eyelinerMakeUp")).getInt("colorId"));
            buffer.writeC(((BasicDBObject) face.get("leftEyePupil")).getInt("_id"));
            buffer.writeC(((BasicDBObject) face.get("leftEyePupil")).getInt("purity"));
            buffer.writeC(((BasicDBObject) face.get("leftEyePupil")).getInt("size"));
            buffer.writeC(((BasicDBObject) face.get("leftEyePupil")).getInt("width"));
            buffer.writeC(((BasicDBObject) face.get("leftEyePupil")).getInt("area"));
            buffer.writeC(((BasicDBObject) face.get("leftEyePupil")).getInt("colorId"));
            buffer.writeC(((BasicDBObject) face.get("leftEyeIris")).getInt("_id"));
            buffer.writeC(((BasicDBObject) face.get("leftEyeIris")).getInt("purity"));
            buffer.writeC(((BasicDBObject) face.get("leftEyeIris")).getInt("size"));
            buffer.writeC(((BasicDBObject) face.get("leftEyeIris")).getInt("width"));
            buffer.writeC(((BasicDBObject) face.get("leftEyeIris")).getInt("area"));
            buffer.writeC(((BasicDBObject) face.get("leftEyeIris")).getInt("colorId"));
            buffer.writeC(((BasicDBObject) face.get("leftEyeLenses")).getInt("_id"));
            buffer.writeC(((BasicDBObject) face.get("leftEyeLenses")).getInt("purity"));
            buffer.writeC(((BasicDBObject) face.get("leftEyeLenses")).getInt("height"));
            buffer.writeC(((BasicDBObject) face.get("leftEyeLenses")).getInt("highlight"));
            buffer.writeC(((BasicDBObject) face.get("leftEyeLenses")).getInt("shine"));
            buffer.writeC(((BasicDBObject) face.get("leftEyeLenses")).getInt("colorId"));
            buffer.writeC(((BasicDBObject) face.get("rightEyePupil")).getInt("_id"));
            buffer.writeC(((BasicDBObject) face.get("rightEyePupil")).getInt("purity"));
            buffer.writeC(((BasicDBObject) face.get("rightEyePupil")).getInt("size"));
            buffer.writeC(((BasicDBObject) face.get("rightEyePupil")).getInt("width"));
            buffer.writeC(((BasicDBObject) face.get("rightEyePupil")).getInt("area"));
            buffer.writeC(((BasicDBObject) face.get("rightEyePupil")).getInt("colorId"));
            buffer.writeC(((BasicDBObject) face.get("rightEyeIris")).getInt("_id"));
            buffer.writeC(((BasicDBObject) face.get("rightEyeIris")).getInt("purity"));
            buffer.writeC(((BasicDBObject) face.get("rightEyeIris")).getInt("size"));
            buffer.writeC(((BasicDBObject) face.get("rightEyeIris")).getInt("width"));
            buffer.writeC(((BasicDBObject) face.get("rightEyeIris")).getInt("area"));
            buffer.writeC(((BasicDBObject) face.get("rightEyeIris")).getInt("colorId"));
            buffer.writeC(((BasicDBObject) face.get("rightEyeLenses")).getInt("_id"));
            buffer.writeC(((BasicDBObject) face.get("rightEyeLenses")).getInt("purity"));
            buffer.writeC(((BasicDBObject) face.get("rightEyeLenses")).getInt("height"));
            buffer.writeC(((BasicDBObject) face.get("rightEyeLenses")).getInt("highlight"));
            buffer.writeC(((BasicDBObject) face.get("rightEyeLenses")).getInt("shine"));
            buffer.writeC(((BasicDBObject) face.get("rightEyeLenses")).getInt("colorId"));
            buffer.writeC(body.getInt("chestMuscles"));
            buffer.writeC(body.getInt("armsMuscles"));
            buffer.writeC(body.getInt("legsMuscles"));
            buffer.writeC(tattoo.getInt("bodyTattooX"));
            buffer.writeC(tattoo.getInt("bodyTattooY"));
            buffer.writeC(tattoo.getInt("bodyTattooRotation"));
            buffer.writeC(tattoo.getInt("bodyTattooWidth"));
            buffer.writeC(tattoo.getInt("bodyTattooHeight"));
            buffer.writeC(tattoo.getInt("bodyTattooDensity"));
            buffer.writeC(tattoo.getInt("bodyTattooShine"));
            buffer.writeC(tattoo.getInt("bodyTattooColorId"));
            buffer.writeB(new byte[7]);
        }
        buffer.writeC(face.getInt("idleAnimationId"));
        buffer.writeC(face.getInt("idleAnimationPower"));
        buffer.writeC(1);
        buffer.writeC(0);
        buffer.writeC(0);
        buffer.writeC(0);
        buffer.writeC(playerAppearance.getInt("voicePitch"));
        buffer.writeC(0);
        buffer.writeC(0);
        buffer.writeC(0);
        buffer.writeS((CharSequence) family, 62);
    }
}
